### ISSUE TITLE
import prefix and variable with the same name

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/sdk#24486]
```
import "dart:math" as math;

class Foo {
  math.Random math = null;
}

main() {
  print (new Foo().math);
}
```

This program runs fine.
Problems:
- import is marked as unused
- no usages of import prefix found
- `math` in `math.Random` resolves to field, but should resolve to import prefix

(Originally reported as https://youtrack.jetbrains.com/issue/WEB-14159)

**Comment by lrhn** [comment]
I think `math` in `math.Random` should resolve to the field, and the type will be malformed because `math.Random` does not refer to to a type in the surrounding scope (the surrounding scope being the instance scope of the class `Foo`). Dart has attempted to only have one lexical scope, independent of the type of declaration, so `math` should refer to the nearest enclosing declaration, which is the `math` field.

That said, I can't find the place in the spec where a type expression is evaluated to a static type, so I can't say if it is actually defined differently.
I find

>A type T is malformed iff:
> • T has the form id or the form pref ix.id, and in the enclosing lexical scope, the name id (respectively pref ix.id) does not denote a type.
> ...

and

> When a class name appears as a type, that name denotes the interface of the class.

In this case, I'd say it doesn't denote a type, but I can't point to the place in the spec that says what a `qualified` actually denotes.

**Comment by alexander-doroshko** [comment]
I'm not a spec guru. If you are right then I guess VM should be fixed to throw an error, and Analysis Server should return the same.

**Comment by lrhn** [comment]
@gbracha @eernstg 
Gilad, can you say what the spec actually says about this?

**Comment by lrhn** [comment]
Dart has only a single way to do identifier resolution. It's not based on the kind of expression the identifier occurs in, it's resolved relative to the surrounding static scope. 
Declarations inside a class can see each other, so from that perspective, the `math.Random` is invalid as a type because `math` refers to the member itself, not the prefix that it shadows.

I still don't think the spec actually says so, but this is the consistent interpretation of the design principles that the spec should be expression.

**Comment by srawlins** [comment]
If we're happy with @lrhn 's response, can I open issues for each impl to detect this at compile time? 

Neither dart2js nor analyzer caught a similar issue. (https://dartpad.dartlang.org/c6a2d93d1465de2047666c59e16d9df4). This is guaranteed to throw at runtime, but never detected at compile/static analysis time, and it could be.

**Comment by lrhn** [comment]
Both VM and dart2js now reports the error when compiled in Dart 2 mode.

**Comment by alexander-doroshko** [comment]
Thanks for the update!
Then I think this issue may be moved to `area-analyzer` to update code highlighting/resolution/error reporting accordingly.
// cc @bwilkerson
