### ISSUE TITLE
Base64 encoder should support the URL-safe alphabet

### ISSUE THREAD

**Issue by nex3** [dart-lang/sdk#24603]
Currently, the Base64 encoder in the core library will reject any Base64 data that includes the `-` or `_` characters, or uses `%3D` as a padding character. Although technically "base64 with URL and filename safe alphabet" is a different encoding, it's likely that users won't realize this or won't know how to distinguish between them and will provide URL-safe base64 to the main encoder. This is particularly likely because the previous standard decoder in `package:crypto` *does* accept this alphabet.

I'm marking this as 1.13 since the base64 converter is a 1.13 feature.

**Comment by lrhn** [comment]
I don't want the core version of base64 to have too many bells and whistles. I'd rather add an extended base64 codec in package:convert.

**Comment by nex3** [comment]
I understand, and I think encoding a URL-safe alphabet should go in `package:convert`. But users will expect that the decoder will decode *all* valid base64. If the input comes from external sources, they may not even be able to control whether it's URL-safe or not. Violating that assumption and rejecting the input will introduce subtle brokenness and incompatibility.

**Comment by mit-mit** [comment]
@lrhn, is that something we can address in 1.13?

**Comment by lrhn** [comment]
That depends on how much time we have until 1.13.
It's pretty easy to make the decoder handle `_` and `-` as input, but not so easy to accept percent-encoded data.
Not supporting `%3D` as padding was a deliberate choice - percent encoding is not part of base-64 at all, it's something that happens when you embed base-64 encoded data in a URI, and it should be undone when you extract the data again (and the `DataUri` class would do that). Putting it into the base-64 codec is bad separation.

**Comment by nex3** [comment]
@lrhn That's arguable. According to [the spec](https://tools.ietf.org/html/rfc4648#section-5):

> The pad character "=" is typically percent-encoded when used in an URI, but if the data length is known implicitly, this can be avoided by skipping the padding; see section 3.2.

Percent-encoding is certainly part of the spec, although what mandate that holds for an implementation is ambiguous. I'd be okay if it wasn't supported by the decoder as long as `_` and `-` are.

**Comment by kevmoo** [comment]
@nex3 Is this addressed with https://codereview.chromium.org/1419983003/ ?
@lrhn can we get this landed and get a merge request in?

**Comment by nex3** [comment]
> Is this addressed with https://codereview.chromium.org/1419983003/ ?

Yep!

**Comment by kevmoo** [comment]
Merge request to get this into 1.13 - https://github.com/dart-lang/sdk/issues/24726

**Comment by lrhn** [comment]
It ended up supporting `%3D` as padding, but no other escapes, and it still does not allow non-alphabet characters inside the encoded data (not even newlines).

**Comment by lrhn** [comment]
Landed and merged into 1.13
