### ISSUE TITLE
Sample on website isn't strong mode compatible (how to streamtransform a UTF8.decoder ?)

### ISSUE THREAD

**Issue by sethladd** [dart-lang/sdk#26366]
From https://www.dartlang.org/docs/tutorials/streams/

The code:

```
import 'dart:io';
import 'dart:async';
import 'dart:convert';

main(args) async {
  var file = new File(args[0]);
  var lines = file
      .openRead()
      .transform(UTF8.decoder)
      .transform(const LineSplitter());
  await for (var line in lines) {
    if (!line.startsWith('#')) {
      print(line);
    }
  }
}
```

Isn't strong mode compliant:

```
~ $ dartanalyzer --strong ~/tmp/test.dart
Analyzing [/Users/sethladd/tmp/test.dart]...
[warning] Unsound implicit cast from Utf8Decoder to StreamTransformer<List<int>, dynamic> (/Users/sethladd/tmp/test.dart, line 9, col 18)
[hint] Unused import (/Users/sethladd/tmp/test.dart, line 2, col 8)
1 warning and 1 hint found.
~ $ 
```

But also, how do I use UTF8.decoder with a StreamTransformer in a strong-mode-world ?

**Comment by floitschG** [comment]
Dupe of issue #25698

**Comment by sethladd** [comment]
Thanks, but it's unclear what I'm supposed to do. What is the recommended way to use Streams, transform, and UTF8.decoder, and be strong-mode compliant?

**Comment by leafpetersen** [comment]
@sethladd That code will silence the type checker, but the cast will fail at runtime on DDC, so it's not really ideal.

This has been fixed in bleeding edge - the strong mode errors that you mention should just go away, I believe, since (e.g.) Utf8Decoder now implements an appropriately typed ChunkedConverter instead of just Converter.  This will land in the next dev release, and then show up in 1.17 as a breaking change.  I believe that Florian is handling the breaking change announcement.

**Comment by floitschG** [comment]
It hasn't been fixed in bleeding edge yet. There is no way to fix this error/warning without breaking existing users.
In the short term, I will create CL next week that people can patch in.
I'm still in discussion if we want to commit the breaking change for next release (1.17) or only for 1.18.

**Comment by sethladd** [comment]
But this hack will work at runtime on the VM?

**Comment by sethladd** [comment]
I think we should reopen this. The sample on the website is still broken, if you are trying to use strong mode.

**Comment by zoechi** [comment]
I just removed an explicit cast on a project of mine that I added a while ago because of that. Also the issue #25698 linked above by floitschG has a recent comment that this is fixed.
