### ISSUE TITLE
Exception from analysis server getNavigation from within SDK file: The method 'then' was called on null (1.22.0-dev.10.6)

### ISSUE THREAD

**Issue by DanTup** [dart-lang/sdk#28732]
### What I was doing

I opened up a Dart project in VS Code / Dart Code, pressed F12 (go to definition) on `close()` on an HttpRequest which took me to `io_sink.dart` in the SDK. I then did D12 on the return type of this method (`Future`) and I got this error from the Analysis Server.

Note: This is with a dev version - 1.22.0-dev.10.6; I was testing it because it was announced that the previous version was an RC (sorry I didn't test this sooner; it's been on my list all week!).

### Versions

- Dart SDK 1.22.0-dev.10.6
- Visual Studio Code 1.9.1
- Dart Code 0.14.9

### Analyzer Info

The analyzer was launched with the arguments:

```text
--client-id=DanTup.dart-code
--client-version=0.14.9
```

### Exception (fatal)

Failed to handle request: {params: {file: m:\Apps\Dart-1.22.0-dev.10.6\lib\io\io_sink.dart, offset: 4266, length: 0}, method: analysis.getNavigation, id: 185}

```text
NoSuchMethodError: The method 'then' was called on null.
Receiver: null
Tried calling: then(Closure: (AnalysisDoneReason) => dynamic)
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      AnalysisDomainHandler.getNavigation.<getNavigation_async_body> (package:analysis_server/src/domain_analysis.dart:177)
#3      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#4      _rootRun (dart:async/zone.dart:1146)
#5      _CustomZone.run (dart:async/zone.dart:1026)
#6      _CustomZone.runGuarded (dart:async/zone.dart:924)
#7      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#8      _rootRun (dart:async/zone.dart:1150)
#9      _CustomZone.run (dart:async/zone.dart:1026)
#10     _CustomZone.runGuarded (dart:async/zone.dart:924)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by DanTup** [comment]
Here's the snippet from the log:

```text
[10:27:40]: ==> {"id":"16","method":"analysis.getNavigation","params":{"file":"m:\\Apps\\Dart-1.20.1\\lib\\io\\io_sink.dart","offset":4268,"length":0}}
[10:27:40]: <== {"error":{"code":"GET_NAVIGATION_INVALID_FILE","message":"Error during `analysis.getNavigation`: invalid file."},"id":"16"}
```

**Comment by bwilkerson** [comment]
Thanks for reporting, but I think this has been fixed on bleeding edge. The code near where the exception was reported looks like:
```
    Future<AnalysisDoneReason> analysisFuture =
        server.onFileAnalysisComplete(file);
    if (analysisFuture == null) {
      server.sendResponse(new Response.getNavigationInvalidFile(request));
      return;
    }
    analysisFuture.then((AnalysisDoneReason reason) async {
```
where the NPE was occurring on the last line. The code now explicitly guards against that case.

**Comment by DanTup** [comment]
Great :-)

**Comment by DanTup** [comment]
@bwilkerson Was it expected that this fix would be in the 1.22.0 SDK released yesterday? A colleague just hit the same thing in the stable release:

### Versions

- Dart SDK 1.22.0
- Visual Studio Code 1.9.1
- Dart Code 0.15.1

### Analyzer Info

The analyzer was launched with the arguments:

```text
--client-id=DanTup.dart-code
--client-version=0.15.1
```

### Exception (fatal)

Failed to handle request: {params: {file: c:\Users\xxxxxxx\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\vector_math-2.0.4\lib\src\vector_math\matrix4.dart, offset: 378, length: 0}, method: analysis.getNavigation, id: 50}

```text
NoSuchMethodError: The method 'then' was called on null.
Receiver: null
Tried calling: then(Closure: (AnalysisDoneReason) => dynamic)
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      AnalysisDomainHandler.getNavigation.<getNavigation_async_body> (package:analysis_server/src/domain_analysis.dart:177)
#3      Future.Future.microtask.<anonymous closure> (dart:async/future.dart:184)
#4      _rootRun (dart:async/zone.dart:1146)
#5      _CustomZone.run (dart:async/zone.dart:1026)
#6      _CustomZone.runGuarded (dart:async/zone.dart:924)
#7      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#8      _rootRun (dart:async/zone.dart:1150)
#9      _CustomZone.run (dart:async/zone.dart:1026)
#10     _CustomZone.runGuarded (dart:async/zone.dart:924)
#11     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:951)
#12     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#14     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

**Comment by bwilkerson** [comment]
> Was it expected that this fix would be in the 1.22.0 SDK released yesterday?

I never have any expectations about which commits will go into which builds. :-)

But looking at the stack trace it appears that the fix isn't in the version being run. The exception is reported to be happening on line 177, but line 177 (on bleeding edge) is the closing brace of the `if` statement; the invocation of `then` is on line 178. The fix was to add the `return` statement inside the `if`, which accounts for the difference in line numbers.

I think we also released the first dev build for the 1.23 release yesterday, and that should have the fix in it.

**Comment by DanTup** [comment]
Fair enough; I'm not sure how builds are taken so didn't know if maybe there was still an issue. We'll test on a 1.23 dev and report back if we still the issue. Thanks!
