### ISSUE TITLE
Crash when printing non-ASCII to PowerShell in Chinese Windows

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/sdk#29101]
A user of Flutter (@goodev) is reporting that the Dart VM crashes when executing `flutter doctor` in PowerShell on his Chinese version of Windows 7:

```shell
PS E:\flutter> flutter doctor
Checking Dart SDK version...
Downloading Dart SDK 1.23.0-dev.9.0...
Unzipping Dart SDK...
Updating flutter tool...
Downloading Material fonts...
Downloading package sky_engine...
Downloading windows-x64 tools...
Downloading android-arm-profile/windows-x64 tools...
Downloading android-arm-release/windows-x64 tools...
Downloading android-x86 tools...
Downloading android-x64 tools...
Downloading android-arm tools...
Downloading android-arm-profile tools...
Downloading android-arm-release tools...
[Unhandled exception:
FileSystemException: writeFrom failed, path = '' (OS Error: æ“�ä½œæˆ�åŠŸå®Œæˆ�ã€‚
, errno = 0)
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:890)
#1      _StdConsumer.addStream.<anonymous closure> (dart:io/stdio.dart:247)
#2      _rootRunUnary (dart:async/zone.dart:1158)
#3      _CustomZone.runUnary (dart:async/zone.dart:1037)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#7      _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#8      _StreamController._add (dart:async/stream_controller.dart:635)
#9      _StreamController.add (dart:async/stream_controller.dart:581)
#10     _StreamSinkImpl.add (dart:io/io_sink.dart:154)
#11     _IOSinkImpl.write (dart:io/io_sink.dart:286)
#12     _StdSinkHelper.write (dart:io/stdio.dart:286)
#13     WindowsStdoutLogger.writeToStdOut (package:flutter_tools/src/base/logger.dart:127)
#14     StdoutLogger.printStatus (package:flutter_tools/src/base/logger.dart:87)
#15     printStatus (package:flutter_tools/src/globals.dart:35)
#16     Doctor.diagnose (package:flutter_tools/src/doctor.dart:149)
<asynchronous suspension>
#17     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:19)
<asynchronous suspension>
#18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:148)
<asynchronous suspension>
#19     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:119)
#20     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:261)
<asynchronous suspension>
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#23     Future.Future.sync (dart:async/future.dart:208)
#24     CommandRunner.run (package:args/command_runner.dart:109)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#26     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#27     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#28     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#29     _rootRun (dart:async/zone.dart:1150)
#30     _CustomZone.run (dart:async/zone.dart:1026)
#31     runZoned (dart:async/zone.dart:1503)
#32     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#33     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#34     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#35     main (file:///E:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#36     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

It crashes when the first non-ASCII character (√) is supposed to be printed. This is happening on the most recent version of PowerShell (version 5). The customer reports that everything works fine in cmd:

```
C:\Users\go>flutter doctor
[√] Flutter (on Microsoft Windows [Version 6.1.7601], channel master)
• Flutter at E:\flutter
• Framework revision 6cd552f (4 hours ago),
• Engine revision 4a5a324669
• Tools Dart version 1.23.0-dev.9.0

[√] Host Executable Compatibility
• Downloaded executables execute on host

[√] Android toolchain - develop for Android devices (Android SDK 25.0.2)
• Android SDK at G:\android\sdk
• Platform android-25, build-tools 25.0.2
• ANDROID_HOME = G:\android\sdk
• Java binary at: D:\ProgramFiles\Java\jdk1.8.0_25\bin\java
• Java version: Java(TM) SE Runtime Environment (build 1.8.0_25-b18)

[√] Android Studio (version 2.3)
• Android Studio at G:\android\studio22
• Gradle version 3.2

[-] Android Studio (version 2.2)
• Android Studio at F:\android-studio
X Gradle version 2.14.1 required. Found version 2.10.
• Try updating or re-installing Android Studio.

[√] IntelliJ IDEA Community Edition (version 2016.3)
• Dart plugin version 163.13137
• Flutter plugin version 0.1.11.1

[-] WebStorm (version 2016.3)
• Flutter plugin not installed; this adds Flutter specific functionality.
• For information about managing plugins, see
https://www.jetbrains.com/help/idea/managing-plugins.html

[√] Connected devices
• None

C:\Users\go>
```

The full discussion of this can be seen on Flutter's github: https://github.com/flutter/flutter/issues/8732.

There was also a report of a user on a German version of Windows, who experienced a similar crash. His problem was resolved by updating to PowerShell 5, though. Details are recorded here: https://github.com/flutter/flutter/issues/8606#issuecomment-284711074.

/cc @zanderso

**Comment by zanderso** [comment]
I think there are two problems here. From the flutter issue, it looks like the message in the OSError is "操作成功完成" which Google translate tells me is "Operation completed successfully." This means that we (or the CRT) are swallowing the error somewhere. That is, _write() is returning < 0, but GetLastError() indicates success. It looks like _write() is more consistent about setting errno on an error, so we should possibly be checking that as well.

The second problem is the failure itself. Looking over the source code of _write(), I'm wondering if the solution here is to skip over the CRT, and call directly into WriteFile and WriteConsoleW. I'm going to investigate doing that.

Having said all that though, it's going to be very tricky to be sure that the problem is fixed without a local reproduction.

**Comment by broislove** [comment]
Hi! I have the same issue both in Cmd and PowerShell.

```
Framework 2017-03-18 21:34:01
Engine ls  Dart 1.23.0-dev.9.0
```

```
Microsoft Windows [Version 6.1.7601]
(c) Корпорация Майкрософт (Microsoft Corp.), 2009. Все права защищены.

C:\Users\Bro>flutter doctor
[Unhandled exception:
FileSystemException: writeFrom failed, path = '' (OS Error: ?z???╡NИ?░NЖ??N? N?N
????╡N????? ?╖?░???╡NИN??╡???░.
, errno = 0)
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:890)
#1      _StdConsumer.addStream.<anonymous closure> (dart:io/stdio.dart:247)
#2      _rootRunUnary (dart:async/zone.dart:1158)
#3      _CustomZone.runUnary (dart:async/zone.dart:1037)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)

#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#7      _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/s
tream_controller.dart:768)
#8      _StreamController._add (dart:async/stream_controller.dart:635)
#9      _StreamController.add (dart:async/stream_controller.dart:581)
#10     _StreamSinkImpl.add (dart:io/io_sink.dart:154)
#11     _IOSinkImpl.write (dart:io/io_sink.dart:286)
#12     _StdSinkHelper.write (dart:io/stdio.dart:286)
#13     WindowsStdoutLogger.writeToStdOut (package:flutter_tools/src/base/logger
.dart:127)
#14     StdoutLogger.printStatus (package:flutter_tools/src/base/logger.dart:87)

#15     printStatus (package:flutter_tools/src/globals.dart:35)
#16     Doctor.diagnose (package:flutter_tools/src/doctor.dart:149)
<asynchronous suspension>
#17     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart
:19)
<asynchronous suspension>
#18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/fl
utter_command.dart:148)
<asynchronous suspension>
#19     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dar
t:119)
#20     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutte
r_command_runner.dart:261)
<asynchronous suspension>
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:
109)
#23     Future.Future.sync (dart:async/future.dart:208)
#24     CommandRunner.run (package:args/command_runner.dart:109)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_comma
nd_runner.dart:157)
#26     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#27     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#28     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base
/context.dart:66)
#29     _rootRun (dart:async/zone.dart:1150)
#30     _CustomZone.run (dart:async/zone.dart:1026)
#31     runZoned (dart:async/zone.dart:1503)
#32     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#33     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#34     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#35     main (file:///C:/flutter/packages/flutter_tools/bin/flutter_tools.dart:8
)
#36     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart
:259)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dar
t:148)

C:\Users\Bro>
```

**Comment by goderbauer** [comment]
Looks like this is not limited to Windows 7. Just got a report with the same problem on Windows 8.1 (French): https://github.com/flutter/flutter/issues/8860#issuecomment-287934153

**Comment by banalg** [comment]
Hello,

Same issue on a French version of Windows 7 SP1, on PowerShell and cmd.

The message **OS Error: LÔÇÖop├®ration a r├®ussi.** means that the operation is successful.
I updated Powershell to version 5.0.10586.117, still having the error... 

Dart VM version: 1.23.0-dev.9.0 (Thu Mar 16 09:53:39 2017) on "windows_x64"

```
PS D:\Dart> flutter doctor
Checking Dart SDK version...
Downloading Dart SDK 1.23.0-dev.9.0...
Unzipping Dart SDK...
Updating flutter tool...
Downloading Material fonts...
Downloading package sky_engine...
Downloading windows-x64 tools...
Downloading android-arm-profile/windows-x64 tools...
Downloading android-arm-release/windows-x64 tools...
Downloading android-x86 tools...
Downloading android-x64 tools...
Downloading android-arm tools...
Downloading android-arm-profile tools...
Downloading android-arm-release tools...
[Unhandled exception:
FileSystemException: writeFrom failed, path = '' (OS Error: LÔÇÖop├®ration a r├®ussi.
, errno = 0)
#0      _RandomAccessFile.writeFromSync (dart:io/file_impl.dart:890)
#1      _StdConsumer.addStream.<anonymous closure> (dart:io/stdio.dart:247)
#2      _rootRunUnary (dart:async/zone.dart:1158)
#3      _CustomZone.runUnary (dart:async/zone.dart:1037)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:932)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:331)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:258)
#7      _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:768)
#8      _StreamController._add (dart:async/stream_controller.dart:635)
#9      _StreamController.add (dart:async/stream_controller.dart:581)
#10     _StreamSinkImpl.add (dart:io/io_sink.dart:154)
#11     _IOSinkImpl.write (dart:io/io_sink.dart:286)
#12     _StdSinkHelper.write (dart:io/stdio.dart:286)
#13     WindowsStdoutLogger.writeToStdOut (package:flutter_tools/src/base/logger.dart:127)
#14     StdoutLogger.printStatus (package:flutter_tools/src/base/logger.dart:87)
#15     printStatus (package:flutter_tools/src/globals.dart:35)
#16     Doctor.diagnose (package:flutter_tools/src/doctor.dart:125)
<asynchronous suspension>
#17     DoctorCommand.runCommand (package:flutter_tools/src/commands/doctor.dart:19)
<asynchronous suspension>
#18     FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:151)
<asynchronous suspension>
#19     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:121)
#20     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#21     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:261)
<asynchronous suspension>
#22     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#23     Future.Future.sync (dart:async/future.dart:208)
#24     CommandRunner.run (package:args/command_runner.dart:109)
#25     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:157)
#26     run.<anonymous closure> (package:flutter_tools/executable.dart:140)
<asynchronous suspension>
#27     AppContext._run (package:flutter_tools/src/base/context.dart:76)
<asynchronous suspension>
#28     AppContext.runInZone.<anonymous closure> (package:flutter_tools/src/base/context.dart:66)
#29     _rootRun (dart:async/zone.dart:1150)
#30     _CustomZone.run (dart:async/zone.dart:1026)
#31     runZoned (dart:async/zone.dart:1503)
#32     AppContext.runInZone (package:flutter_tools/src/base/context.dart:65)
#33     run (package:flutter_tools/executable.dart:113)
<asynchronous suspension>
#34     main (package:flutter_tools/executable.dart:66)
<asynchronous suspension>
#35     main (file:///D:/Dart/flutter/packages/flutter_tools/bin/flutter_tools.dart:8)
#36     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#37     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```
