### ISSUE TITLE
`dartanalyzer .` crashes on pkg/glob

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#29288]
With 1.23.0-dev.11.5

```console
$ git clone https://github.com/dart-lang/glob
$ cd glob
$ pub upgrade
$ dartanalyzer .
Analyzing glob...
Unhandled exception:
NoSuchMethodError: The getter 'isSynthetic' was called on null.
Receiver: null
Tried calling: isSynthetic
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _IndexContributor.recordRelationOffset (package:analyzer/src/dart/analysis/index.dart:448)
#3      _IndexContributor.recordRelation (package:analyzer/src/dart/analysis/index.dart:413)
#4      _IndexContributor.visitSimpleIdentifier (package:analyzer/src/dart/analysis/index.dart:683)
#5      SimpleIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:9413)
#6      LabelImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:6938)
#7      GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#8      GeneralizingAstVisitor.visitLabel (package:analyzer/dart/ast/visitor.dart:386)
#9      LabelImpl.accept (package:analyzer/src/dart/ast/ast.dart:6934)
#10     NamedExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:7768)
#11     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#12     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:284)
#13     GeneralizingAstVisitor.visitNamedExpression (package:analyzer/dart/ast/visitor.dart:419)
#14     NamedExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:7764)
#15     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#16     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)
#17     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#18     GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:162)
#19     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)
#20     _IndexContributor.visitMethodInvocation (package:analyzer/src/dart/analysis/index.dart:608)
#21     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7657)
#22     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#23     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)
#24     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#25     GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:162)
#26     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)
#27     _IndexContributor.visitMethodInvocation (package:analyzer/src/dart/analysis/index.dart:608)
#28     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7657)
#29     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4261)
#30     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#31     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:494)
#32     GeneralizingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:291)
#33     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4257)
#34     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#35     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#36     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#37     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:494)
#38     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:184)
#39     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#40     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)
#41     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#42     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:314)
#43     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:187)
#44     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#45     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5360)
#46     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#47     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:284)
#48     GeneralizingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:325)
#49     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5354)
#50     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#51     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)
#52     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#53     GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:162)
#54     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)
#55     _IndexContributor.visitMethodInvocation (package:analyzer/src/dart/analysis/index.dart:608)
#56     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7657)
#57     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4261)
#58     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#59     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:494)
#60     GeneralizingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:291)
#61     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4257)
#62     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#63     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#64     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#65     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:494)
#66     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:184)
#67     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#68     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)
#69     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#70     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:314)
#71     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:187)
#72     BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#73     FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5360)
#74     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#75     GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:284)
#76     GeneralizingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:325)
#77     FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5354)
#78     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#79     ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)
#80     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#81     GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:162)
#82     ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)
#83     _IndexContributor.visitMethodInvocation (package:analyzer/src/dart/analysis/index.dart:608)
#84     MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7657)
#85     ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4261)
#86     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#87     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:494)
#88     GeneralizingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:291)
#89     ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4257)
#90     NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#91     BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#92     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#93     GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:494)
#94     GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:184)
#95     BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#96     BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)
#97     GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#98     GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:314)
#99     GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:187)
#100    BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#101    FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5360)
#102    GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#103    GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:284)
#104    GeneralizingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:325)
#105    FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5354)
#106    NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#107    ArgumentListImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:431)
#108    GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#109    GeneralizingAstVisitor.visitArgumentList (package:analyzer/dart/ast/visitor.dart:162)
#110    ArgumentListImpl.accept (package:analyzer/src/dart/ast/ast.dart:427)
#111    _IndexContributor.visitMethodInvocation (package:analyzer/src/dart/analysis/index.dart:608)
#112    MethodInvocationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7657)
#113    ExpressionStatementImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:4261)
#114    GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#115    GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:494)
#116    GeneralizingAstVisitor.visitExpressionStatement (package:analyzer/dart/ast/visitor.dart:291)
#117    ExpressionStatementImpl.accept (package:analyzer/src/dart/ast/ast.dart:4257)
#118    NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#119    BlockImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1358)
#120    GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#121    GeneralizingAstVisitor.visitStatement (package:analyzer/dart/ast/visitor.dart:494)
#122    GeneralizingAstVisitor.visitBlock (package:analyzer/dart/ast/visitor.dart:184)
#123    BlockImpl.accept (package:analyzer/src/dart/ast/ast.dart:1354)
#124    BlockFunctionBodyImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:1302)
#125    GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#126    GeneralizingAstVisitor.visitFunctionBody (package:analyzer/dart/ast/visitor.dart:314)
#127    GeneralizingAstVisitor.visitBlockFunctionBody (package:analyzer/dart/ast/visitor.dart:187)
#128    BlockFunctionBodyImpl.accept (package:analyzer/src/dart/ast/ast.dart:1298)
#129    FunctionExpressionImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5360)
#130    GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#131    GeneralizingAstVisitor.visitExpression (package:analyzer/dart/ast/visitor.dart:284)
#132    GeneralizingAstVisitor.visitFunctionExpression (package:analyzer/dart/ast/visitor.dart:325)
#133    FunctionExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:5354)
#134    FunctionDeclarationImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:5204)
#135    GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#136    GeneralizingAstVisitor.visitAnnotatedNode (package:analyzer/dart/ast/visitor.dart:156)
#137    GeneralizingAstVisitor.visitDeclaration (package:analyzer/dart/ast/visitor.dart:247)
#138    GeneralizingAstVisitor.visitCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:222)
#139    GeneralizingAstVisitor.visitNamedCompilationUnitMember (package:analyzer/dart/ast/visitor.dart:416)
#140    GeneralizingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:318)
#141    FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5197)
#142    NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#143    CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2523)
#144    GeneralizingAstVisitor.visitNode (package:analyzer/dart/ast/visitor.dart:431)
#145    GeneralizingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:219)
#146    CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#147    _IndexAssembler.assemble (package:analyzer/src/dart/analysis/index.dart:240)
#148    indexUnit (package:analyzer/src/dart/analysis/index.dart:37)
#149    AnalysisDriver._serializeResolvedUnit (package:analyzer/src/dart/analysis/driver.dart:1171)
#150    AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:958)
#151    PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1671)
#152    AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:940)
#153    AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:491)
<asynchronous suspension>
#154    AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:131)
<asynchronous suspension>
#155    AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:175)
<asynchronous suspension>
#156    AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:121)
<asynchronous suspension>
#157    Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:699)
<asynchronous suspension>
#158    Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:245)
<asynchronous suspension>
#159    Driver._analyzeAll (package:analyzer_cli/src/driver.dart:167)
<asynchronous suspension>
#160    Driver.start (package:analyzer_cli/src/driver.dart:146)
<asynchronous suspension>
#161    main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:11)
#162    _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#163    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:995)
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1671)
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:940)
#3      AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:491)
<asynchronous suspension>
#4      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:131)
<asynchronous suspension>
#5      AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:175)
<asynchronous suspension>
#6      AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:121)
<asynchronous suspension>
#7      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:699)
<asynchronous suspension>
#8      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:245)
<asynchronous suspension>
#9      Driver._analyzeAll (package:analyzer_cli/src/driver.dart:167)
<asynchronous suspension>
#10     Driver.start (package:analyzer_cli/src/driver.dart:146)
<asynchronous suspension>
#11     main (file:///b/build/slave/dart-sdk-mac-dev/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:11)
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by kevmoo** [comment]
Just verified that this does **NOT** happen on 1.22.1.

qed: regression

**Comment by kevmoo** [comment]
and also with pkg/firebase

```
AnalysisException: Element mismatch in /tmp/pana.1491503515782.k1932Z/hosted/pub.dartlang.org/firebase-3.0.1/test/auth_test.dart at /tmp/pana.1491503515782.k1932Z/hosted/pub.dartlang.org/firebase-3.0.1/test/auth_test.dart
Caused by Bad state: Found 1 annotation nodes and 0 element annotations
#0      DeclarationResolver._resolveAnnotations (package:analyzer/src/generated/declaration_resolver.dart:516)
#1      DeclarationResolver.visitImportDirective (package:analyzer/src/generated/declaration_resolver.dart:313)
#2      ImportDirectiveImpl.accept (package:analyzer/src/dart/ast/ast.dart:6186)
#3      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:8052)
#4      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2522)
#5      RecursiveAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:707)
#6      CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2516)
#7      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:49)
#8      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:511)
#9      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:89)
#10     _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#11     LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:88)
#12     AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:954)
#13     PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1671)
#14     AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:940)
#15     AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:491)
<asynchronous suspension>
#16     AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:131)
<asynchronous suspension>
#17     AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:175)
<asynchronous suspension>
#18     AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:121)
<asynchronous suspension>
#19     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:699)
<asynchronous suspension>
#20     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:245)
<asynchronous suspension>
#21     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:167)
<asynchronous suspension>
#22     Driver.start (package:analyzer_cli/src/driver.dart:146)
<asynchronous suspension>
#23     main (file:///tmp/tmpuOsKpF/dart-1.23.0-dev.11.5/dart/pkg/analyzer_cli/bin/analyzer.dart:11)
#24     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)


#0      DeclarationResolver.resolve (package:analyzer/src/generated/declaration_resolver.dart:52)
#1      LibraryAnalyzer._resolveFile (package:analyzer/src/dart/analysis/library_analyzer.dart:511)
#2      LibraryAnalyzer.analyze.<anonymous closure> (package:analyzer/src/dart/analysis/library_analyzer.dart:89)
#3      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:356)
#4      LibraryAnalyzer.analyze (package:analyzer/src/dart/analysis/library_analyzer.dart:88)
#5      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:954)
#6      PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1671)
#7      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:940)
#8      AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:491)
<asynchronous suspension>
#9      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:131)
<asynchronous suspension>
#10     AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:175)
<asynchronous suspension>
#11     AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:121)
<asynchronous suspension>
#12     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:699)
<asynchronous suspension>
#13     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:245)
<asynchronous suspension>
#14     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:167)
<asynchronous suspension>
#15     Driver.start (package:analyzer_cli/src/driver.dart:146)
<asynchronous suspension>
#16     main (file:///tmp/tmpuOsKpF/dart-1.23.0-dev.11.5/dart/pkg/analyzer_cli/bin/analyzer.dart:11)
#17     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)

#0      AnalysisDriver._computeAnalysisResult.<anonymous closure> (package:analyzer/src/dart/analysis/driver.dart:995)
#1      PerformanceLog.run (package:analyzer/src/dart/analysis/driver.dart:1671)
#2      AnalysisDriver._computeAnalysisResult (package:analyzer/src/dart/analysis/driver.dart:940)
#3      AnalysisDriver.getErrors (package:analyzer/src/dart/analysis/driver.dart:491)
<asynchronous suspension>
#4      AnalyzerImpl.prepareErrors (package:analyzer_cli/src/analyzer_impl.dart:131)
<asynchronous suspension>
#5      AnalyzerImpl._analyze (package:analyzer_cli/src/analyzer_impl.dart:175)
<asynchronous suspension>
#6      AnalyzerImpl.analyze (package:analyzer_cli/src/analyzer_impl.dart:121)
<asynchronous suspension>
#7      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:699)
<asynchronous suspension>
#8      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:245)
<asynchronous suspension>
#9      Driver._analyzeAll (package:analyzer_cli/src/driver.dart:167)
<asynchronous suspension>
#10     Driver.start (package:analyzer_cli/src/driver.dart:146)
<asynchronous suspension>
#11     main (file:///tmp/tmpuOsKpF/dart-1.23.0-dev.11.5/dart/pkg/analyzer_cli/bin/analyzer.dart:11)
#12     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

**Comment by bwilkerson** [comment]
I can reproduce the first case on bleeding edge. I tried to reproduce the second by executing
```
$ git clone https://github.com/firebase/firebase-dart.git
$ cd firebase-dart/
$ pub upgrade
$ dartanalyzer .
```
and there was no exception. Instead I got five hints:
```
Analyzing firebase-dart...
     hint • 'throws' is deprecated and shouldn't be used at test/database_test.dart:234:71 • deprecated_member_use
     hint • 'throws' is deprecated and shouldn't be used at test/database_test.dart:260:73 • deprecated_member_use
     hint • 'throws' is deprecated and shouldn't be used at test/database_test.dart:284:13 • deprecated_member_use
     hint • 'throws' is deprecated and shouldn't be used at test/database_test.dart:443:13 • deprecated_member_use
     hint • 'throws' is deprecated and shouldn't be used at test/database_test.dart:448:13 • deprecated_member_use
5 hints found.
```
I suspect that means the the bug has been fixed but that the fix hasn't been cherry-picked. Unfortunately, I don't know which CL(s) need to be cherry picked in order to get the fix.

**Comment by kevmoo** [comment]
For the 2nd one, delete `.packages` and/or `pubspec.lock`.

Or just sync to a new direction w/out running `pub upgrade`

**Comment by scheglov** [comment]
CL for `glob`.
https://codereview.chromium.org/2799093007

**Comment by scheglov** [comment]
The 2nd problem (with `firebase`) is equivalent to analysis of the following code:
```dart
@foo
import 'bar:baz';
```

Basically, if a URI is not resolved to a `Source`, we don't create `ImportElement` for it, so there is nothing to get annotation elements for annotation nodes.

See also #29188 for a similar problem.

**Comment by scheglov** [comment]
The first problem [is fixed](https://github.com/dart-lang/sdk/commit/ee89054fe988f1ecf7bcd997a7c71f8ff840579a).

**Comment by scheglov** [comment]
The fix for the 2nd problem would require quite a big change to analyzer in order to create `ImportElement`s for unresolved `Source`s. So, I think it is better to do in `1.24`.

**Comment by scheglov** [comment]
[CL](https://codereview.chromium.org/2809523002) for the 2nd problem.

**Comment by scheglov** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/021d99e05deae069352f5b8d2c00f1ef0b1f00f3.
