### ISSUE TITLE
Please, clarify how Stream.isEmpty handles errors

### ISSUE THREAD

**Issue by alsemenov** [dart-lang/sdk#29730]
The [description](https://api.dartlang.org/stable/1.23.0/dart-async/Stream/isEmpty.html) of dart:async:Stream.isEmpty reads:

> Future&lt;bool&gt; isEmpty
> Reports whether this stream contains any elements.
> 
> Stops listening to the stream after the first element has been received.
> 
> Internally the method cancels its subscription after the first element. This means that single-subscription (non-broadcast) streams are closed and cannot be reused after a call to this getter.

Please, clarify how errors in stream are handled? Will the returned future be completed with the first error in the stream or with value false?

**Comment by lrhn** [comment]
Also addressed by https://codereview.chromium.org/2899273003/

**Comment by lrhn** [comment]
Update landed.

**Comment by alsemenov** [comment]
The issue is closed for more than month now. Several SDK versions has been released (1.24.0, 1.24.1, 1.24.2), but [description](https://api.dartlang.org/stable/1.24.2/dart-async/Stream/isEmpty.html) of dart:async:Stream.isEmpty is still the same. Could you clarify the version in which changes will appear?
This will prevent several new issues about vague method descriptions.
