### ISSUE TITLE
Flutter engine build broken against Dart SDK at top of tree.

### ISSUE THREAD

**Issue by zanderso** [dart-lang/sdk#30118]
The build was broken by https://github.com/dart-lang/sdk/commit/b71bd543a98c903117045304d2175f02b5714c9a with build error:

```
[13/16] ACTION //flutter/lib/snapshot:flutter_patched_sdk(//build/toolchain/mac:ios_clang_arm)
FAILED: flutter_patched_sdk/platform.dill 
python ../../dart/tools/patch_sdk.py --quiet flutter /Users/zra/flutter/engine/src/dart/sdk /Users/zra/flutter/engine/src/out/ios_release/gen/flutter/lib/snapshot/patches flutter_patched_sdk /Users/zra/flutter/engine/src/dart/.packages
Not enabling colors, stdout does not support ANSI colors.
flutter_patched_sdk/lib/async/async.dart:112:13: Error: Expected a function body or '=>'.
_fatal(msg) native "DartAsync_fatal";
            ^
Unhandled exception:
flutter_patched_sdk/lib/async/async.dart:112:13: Error: Expected a function body or '=>'.
_fatal(msg) native "DartAsync_fatal";
            ^
#0      defaultErrorHandler (package:front_end/compiler_options.dart:16:53)
#1      ProcessedOptions.reportError (package:front_end/src/base/processed_options.dart:113:10)
#2      List.forEach (dart:core-patch/growable_array.dart:256)
#3      generateKernelInternal (package:front_end/src/kernel_generator_impl.dart:140:27)
<asynchronous suspension>
#4      generateKernel.<anonymous closure> (package:front_end/src/kernel_generator_impl.dart:37:18)
<asynchronous suspension>
#5      CompilerContext.withGlobalOptions.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:45:33)
#6      _rootRun (dart:async/zone.dart:1120)
#7      _CustomZone.run (dart:async/zone.dart:1001)
#8      runZoned (dart:async/zone.dart:1467)
#9      CompilerContext.withGlobalOptions (package:front_end/src/fasta/compiler_context.dart:45:12)
#10     CompilerCommandLine.withGlobalOptions (package:front_end/src/fasta/compiler_command_line.dart:120:28)
#11     generateKernel (package:front_end/src/kernel_generator_impl.dart:32:36)
<asynchronous suspension>
#12     compilePlatform (file:///Users/zra/flutter/engine/src/dart/tools/patch_sdk.dart:214:22)
<asynchronous suspension>
#13     _main (file:///Users/zra/flutter/engine/src/dart/tools/patch_sdk.dart:134:13)
<asynchronous suspension>
#14     main (file:///Users/zra/flutter/engine/src/dart/tools/patch_sdk.dart:60:11)
<asynchronous suspension>
#15     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:263)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
Traceback (most recent call last):
  File "../../dart/tools/patch_sdk.py", line 55, in <module>
    sys.exit(main())
  File "../../dart/tools/patch_sdk.py", line 51, in main
    subprocess.check_call([options.dart_executable, dart_file] + args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/zra/dart/sdk/tools/sdks/mac/dart-sdk/bin/dart', '../../dart/tools/patch_sdk.dart', 'flutter', '/Users/zra/flutter/engine/src/dart/sdk', '/Users/zra/flutter/engine/src/out/ios_release/gen/flutter/lib/snapshot/patches', 'flutter_patched_sdk', '/Users/zra/flutter/engine/src/dart/.packages']' returned non-zero exit status 255
```

**Comment by mraleph** [comment]
Which configuration/build target is this? We need to check why flutter TOT bot did not catch this. It seems to be building fine there (even though the bot is completely red... probably because somebody on the Flutter team ignored the build breakage).

**Comment by zanderso** [comment]
Release iOS. Maybe related to clean vs incremental build?

**Comment by mkustermann** [comment]
I've sent out [cl/565503](https://chromium-review.googlesource.com/c/565503/) which should fix the first reason why flutter TOT build is red.

Once this lands, it should continue to do more building after the analyzer step, so it should also catch a broken build of "flutter_patched_sdk".

**Comment by sigmundch** [comment]
@zanderso does Martin's CL fix the issue, or is there something else I should be looking into?

If you need me to dig deeper, can you send me some pointers for how to reproduce the issue?

**Comment by sigmundch** [comment]
Actually - I see where the issue is from, will send a CL shortly

**Comment by zanderso** [comment]
@sigmundch, @mkustermann's patch clears up the failures on the buildbot that were masking this failure. This failure is still present. To reproduce, follow the instructions here for checking out and building the Flutter engine: https://github.com/flutter/engine/blob/master/CONTRIBUTING.md. Then, replace flutter/engine/src/dart with a checkout of top-of-tree Dart SDK.

**Comment by sigmundch** [comment]
https://codereview.chromium.org/2980513002/

**Comment by sigmundch** [comment]
Sorry again for the break and thanks for the repro details. I was able to verify locally that my CL addresses the issue.

**Comment by zanderso** [comment]
Thanks!
