### ISSUE TITLE
Fix handling of integer literals in common front-end according to the spec

### ISSUE THREAD

**Issue by alexmarkov** [dart-lang/sdk#31339]
Currently, common front-end is overly restrictive for integer literals in --limit-ints-to-64-bits mode and rejects certain literals which are allowed according to the informal spec (https://github.com/dart-lang/sdk/blob/master/docs/language/informal/int64.md).

* It doesn't allow -9223372036854775808 (MIN_INT64) literal - it interprets such literal as unary minus applied to 9223372036854775808 literal which is out of range.
* It doesn't allow hexadecimal literals > MAX_INT64 (spec allows unsigned 64-bit hex literals).

**Comment by alexmarkov** [comment]
The following test currently fails:
```
tools/test.py -m release -c dartkp -r dart_precompiled vm/dart/truncating_ints_test
```

**Comment by sjindel-google** [comment]
The front-end is actually not over-restrictive in these cases, it's the VM which is reporting compile-time there. The CFE currently allows these other other invalid literals.

**Comment by alexmarkov** [comment]
More details about how CFE handles integer literals now:

1. CFE parses '-' in integer literals as unary minus, so it parses -9223372036854775808 and unary minus applied to a literal 9223372036854775808, and the literal 9223372036854775808 is out of range.

2. To convert string representation of a literal to int, CFE uses int.parse. So, in --limit-ints-to-64-bits mode it will reject incorrect literals which are out of range, and also 9223372036854775808.

3. int.parse is currently too restrictive for hexadecimal literals. As CFE relies on int.parse, it also depends on fixing https://github.com/dart-lang/sdk/issues/31369.

4. int.parse() detects if integers are fixed-size at compile time. It means that kernel-service, which is converted to a snapshot without --limit-ints-to-64-bits, does not get proper semantics in int.parse. To test CFE with fixed-size integers either use '-c dartkp --strong' mode (it runs without kernel service), or, at the command line specify kernel service .dart file, not snapshot:

```
out/ReleaseX64/dart --limit-ints-to-64-bits --dfe=pkg/vm/bin/kernel_service.dart --kernel-binaries=out/ReleaseX64 tests/language_2/int64_literal_test.dart
```

**Comment by sjindel-google** [comment]
Fixed via https://dart-review.googlesource.com/c/sdk/+/27800.

**Comment by floitschG** [comment]
Test started failing again with additional code from Alex.

**Comment by alexmarkov** [comment]
I'll take a look. I think now CFE has a correct support for limited integers, and the failures could be caused by the CFE itself running without --limit-ints-to-64-bits.

**Comment by alexmarkov** [comment]
* As I thought, in precompiler mode CFE itself runs on the VM without --limit-ints-to-64-bits, so it is not getting correct int.parse() and is not able to correctly parse literals. Will fix it in https://dart-review.googlesource.com/c/sdk/+/29546.

* @sjindel-google, even with your changes in int.parse() it is still not able to parse unsigned hexadecimal literals. So correct parsing of literals in CFE is still gated on https://github.com/dart-lang/sdk/issues/31369. @floitschG, could you please take a look at the int.parse implementation?

**Comment by sjindel-google** [comment]
I'm not able to reproduce the erroneous behaviour:
```
$ cat test.dart
void main() {
  int x = int.parse("0xffffffffffffffff");
  print(x);
}
$ out/ReleaseX64/dart --dfe=pkg/vm/bin/kernel_service.dart --kernel-binaries=out/ReleaseX64 --strong --reify-generic-functions --limit-ints-to-64-bits --pac
kages=$HOME/src/dart-sdk/sdk/.packages test.dart                                                                                                            
-1
```

**Comment by alexmarkov** [comment]
You're right: it works if tested with a simple test. It doesn't work if tests run in '-c dartkp --strong' mode using the test tool.

After a little bit more digging I found that when running tests in dartkp mode CFE runs on a stable checked-in Dart SDK. That SDK obviously doesn't have your changes, so int.parse was rejecting hex literals.

To summarize, the remaining problem is to make CFE run on the fresh Dart SDK and with --limit-ints-to-64-bits. I'll keep looking into it.

I'm sorry for this noise.

Off-topic: when CFE will be used in dart2js/DDC, it will still run on Dart VM with limited integers. Do we want the same limitations be applied to integer literals when compiling dart code to JS? If not, then CFE should do something more sophisticated than int.parse.

**Comment by alexmarkov** [comment]
To the best of my knowledge common front-end has all necessary support for Dart 2.0 fixed-size integers.
