### ISSUE TITLE
Not existing files cause uncaught exception from CFE.

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#33719]
For example:

```dart
import 'does_not_exist.dart';
```

Exception should not leave CFE, and should be reported as compilation errors.

```
  Crash when compiling package:test/foo.dart,
  at character offset null:
  FileSystemException(path=package:test/foo.dart; message=Not found)
  #0      _FileSystemEntityAdaptor.readAsBytes (package:analyzer/src/dart/analysis/frontend_resolution.dart:487:7)
  <asynchronous suspension>
  #1      SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:154:65)
  <asynchronous suspension>
  #2      SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:192:26)
  <asynchronous suspension>
  #3      Loader.buildOutlines (package:front_end/src/fasta/loader.dart:176:13)
  <asynchronous suspension>
  #4      KernelTarget.buildOutlines.<anonymous closure> (package:front_end/src/fasta/kernel/kernel_target.dart:235:24)
  <asynchronous suspension>
  #5      withCrashReporting (package:front_end/src/fasta/deprecated_problems.dart:67:24)
  <asynchronous suspension>
  #6      KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:232:12)
  <asynchronous suspension>
  #7      FrontEndCompiler.compile.<anonymous closure>.<anonymous closure> (package:analyzer/src/dart/analysis/frontend_resolution.dart:227:30)
```

**Comment by stefantsov** [comment]
I guess this one was fixed by someone at some point.

To verify this I've written the following program in `/tmp/asdf.dart`:

```dart
import 'lkajsdfjalfjalkjdf.dart';

main() {}
```

It gives the following output when being compiled:

```
file:///tmp/lkajsdfjalfjalkjdf.dart:1: Error: No such file or directory
library;
import self as self;

static method #main() → dynamic {
  throw "file:///tmp/lkajsdfjalfjalkjdf.dart:1: Error: No such file or directory";
}
```

@scheglov Could you verify that the issue is resolved?

**Comment by scheglov** [comment]
I'm [updating](https://dart-review.googlesource.com/c/sdk/+/64021) the implementation of `FileSystemEntity` in Analyzer, to throw `FileSystemException` when the file does not exist. The exception does not leave CFE now.

But as you can see, https://github.com/dart-lang/sdk/issues/33686 still happens - we throw from `main`. I don't know if we want to keep all the similar problem be tracked there, or each instance should be fixed individually, so requires a separate issue, like this one.

**Comment by stefantsov** [comment]
Ok, I think I need a clarification here: are we talking about an exception thrown at compile time or at run time?

In my previous message I assume that it's an exception thrown by the compiler during compile time.  At least, that's how I read the title of this GitHub issue.  That's why I've invoked just the compiler and saw now exceptions thrown from it.  There was, however, an exception in the output program that would be thrown if the program was run.

So, I think if this GitHub issue is about an exception thrown during compile time, it should be closed.  If it's about the exception in the output program that would manifest itself during run time, it should be renamed and the description should be changed.  And if that's the case, it's clearly a sub-issue of https://github.com/dart-lang/sdk/issues/33686, as suggested.

**Comment by scheglov** [comment]
It was an exception during compile time.
So, yes, formally this issue, with its initial title and message is fixed.
Feel free to close it.

I'm mentioning #33686 because it seems that there might be different paths leading toward `deprecated_InputError`, and requiring different solution, so it might be useful to track them separately. If this is not something useful and all of them will be fixed at once, that is fine with me too :-)

**Comment by stefantsov** [comment]
Got it.  I think those two, the original exception at compile time and an execution path leading to deprecated_InputError should be tracked separately.  I'm closing this one and will create a specific sub-issue for https://github.com/dart-lang/sdk/issues/33686.

**Comment by stefantsov** [comment]
I've created a list of causes for deprecated_InputError in https://github.com/dart-lang/sdk/issues/33686.  This issue is references there, so I think there's no need to open another issue for that.
