### ISSUE TITLE
Analyzer issues incorrect warning on inconsistent interfaces in mixin inference

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/sdk#34404]
The analyzer issues the following warnings on the code below:

```
  error • Type parameters could not be inferred for the mixin 'M1' because the base class implements the mixin's supertype constraint 'I<T>' in multiple conflicting ways at /Users/leafp/tmp/ddctest.dart:10:33 • mixin_inference_inconsistent_matching_classes
  error • A value of type 'int' can't be assigned to a variable of type 'String' at /Users/leafp/tmp/ddctest.dart:13:14 • invalid_assignment
 ```

Note that the second (expected) error does imply that the mixin inference is succeeding and inferring `int` as the type argument, but nonetheless the first (unexpected) error is emitted as if inference had failed.

```dart
class I<X> {}

class M0<T> extends I<T> {}

class M1<T> extends I<T> {
  T foo() => null;
}

// M1 is inferred as M1<int>
class A extends I<int> with M0, M1 {}

void main () {
  String s = new A().foo();
}
```

**Comment by leafpetersen** [comment]
cc @bwilkerson @stereotype441 @yjbanov 

This doesn't need to be fixed for the old super-mixin inference, but we need to be sure this works correctly with the new syntax since flutter uses this pattern.  I'll try to get some tests landed for this.

**Comment by jmesserly** [comment]
FYI, this may have been fixed(?). Not sure though. The errors I see now are:
```
  error • The class 'M0' can't be used as a mixin because it extends a class other than Object at test.dart:10:29 • mixin_inherits_from_not_object
  error • The class 'M1' can't be used as a mixin because it extends a class other than Object at test.dart:10:33 • mixin_inherits_from_not_object
  error • A value of type 'int' can't be assigned to a variable of type 'String' at test.dart:13:14 • invalid_assignment
```

**Comment by jmesserly** [comment]
if I change `extends` to `implements` I get this error:
```
  error • The class 'A' cannot implement both 'I<int>' and 'I<dynamic>' because the type arguments are different at test.dart:10:1 • conflicting_generic_interfaces
```
That makes me think the inference may not be working correctly.

**Comment by leafpetersen** [comment]
There is no inference for implements clauses, so the errors are expected for the class example.  For mixins, the proposal [here](https://github.com/dart-lang/language/blob/master/working/0006.%20Super-invocations%20in%20mixins/0007.%20Mixin%20declarations/lrhn-strawman.md) includes a section on inference, specified [here](https://github.com/dart-lang/language/blob/master/working/0006.%20Super-invocations%20in%20mixins/0007.%20Mixin%20declarations/mixin-inference.md).  I just landed tests for this [here](https://dart-review.googlesource.com/c/sdk/+/74017).

**Comment by stereotype441** [comment]
I'll look into this

**Comment by leafpetersen** [comment]
This is the relevant reproduction for the new mixin syntax:

```dart
class I<X> {}

mixin M0<T> on I<T> {}

mixin M1<T> on I<T> {
  T foo() => null;
}

class A = I<int> with M0, M1;

void main () {
  String s = new A().foo();
}
```

I still see the incorrect error for this example (and actually don't see the correct error).

I believe that this case is covered by the tests that I added.

**Comment by leafpetersen** [comment]
Note that this will be a blocker for migrating flutter.  cc @JekCharlsonYu

**Comment by leafpetersen** [comment]
cc @yjbanov

**Comment by yjbanov** [comment]
Thanks for looking into it! [Here a place in Flutter](https://github.com/flutter/flutter/blob/a07d3719a1fe58c0c43ffde7079be291640fa98b/packages/flutter/lib/src/widgets/dismissible.dart#L190) where we have to ignore an analyzer warning when inference fails.

**Comment by stereotype441** [comment]
A fix for the repro in https://github.com/dart-lang/sdk/issues/34404#issuecomment-422543630 is out for review: https://dart-review.googlesource.com/c/sdk/+/75625.

There are still a few of Leaf's test cases failing, so I'm going to leave this issue open until I've addressed them.

**Comment by stereotype441** [comment]
With 2e3f17fa2bf97f29d82a29b6fc42ccd5c9e0f350, the analyzer now produces the expected behavior for Leaf's example in https://github.com/dart-lang/sdk/issues/34404#issuecomment-422543630.  But that same example fails when the analyzer is run with the "--supermixin" flag is passed in.  The example at the top of this bug report also sill fails.

@yjbanov's Flutter code is in a similar situation: if I modify it to use "mixin" syntax and analyze it without "--supermixin", it works.  But if I analyze it with "--supermixin", it fails (regardless of whether old or new syntax is used).

So I think we are no longer blocking flutter's migration to the new syntax.  And I'm mindful of Leaf's statement that this doesn't need to be fixed for the old super-mixin inference.  But I'm bothered by the fact that the presence of the "--supermixin" flag mysteriously affects the new mixin syntax as well--that really shouldn't happen.  So I'm going to continue investigating for a bit longer.

**Comment by stereotype441** [comment]
Aha, glad I checked.  Supermixin error checking is still not working, but it *looks like* it's working because it's disabled when the "--supermixin" flag is missing.  Working on a fix.

**Comment by stereotype441** [comment]
Candidate fix out for review: https://dart-review.googlesource.com/c/sdk/+/75792.  This fixes and enables the error checking, and as a bonus, it fixes the test case in the original bug report (that uses the old "--supermixin" syntax).
