### ISSUE TITLE
Analyzer has difficulty resolving exported dart:ui symbols

### ISSUE THREAD

**Issue by jonahwilliams** [dart-lang/sdk#36346]
When attempting to build flutter/flutter using an analyzer summary containing a web compatible dart:ui with dartdevc, we're getting many analysis errors resulting from failing to resolve types that have been re-exported from dart:ui. Compiling a program that only contains dart:ui works correctly, however.

For example, `VoidCallback` is a typedef defined in dart:ui.

```
[error] Undefined class 'VoidCallback'. (package:flutter/src/semantics/semantics.dart, line 837, col 9)
[error] Undefined class 'VoidCallback'. (package:flutter/src/semantics/semantics.dart, line 847, col 9)
[error] Undefined class 'VoidCallback'. (package:flutter/src/semantics/semantics.dart, line 860, col 9)
[error] Undefined class 'VoidCallback'. (package:flutter/src/semantics/semantics.dart, line 873, col 9)
[error] Undefined class 'VoidCallback'. (package:flutter/src/semantics/semantics.dart, line 886, col 9)
```

In `src/semantics/semantics.dart` our imports look like:

```
import 'dart:math' as math;
import 'dart:typed_data';
import 'dart:ui' as ui;
import 'dart:ui' show Offset, Rect, SemanticsAction, SemanticsFlag,
       TextDirection;

import 'package:flutter/foundation.dart'; // <- VoidCallback re-exported from here.
import 'package:flutter/painting.dart' show MatrixUtils, TransformProperty;
import 'package:flutter/services.dart';
import 'package:vector_math/vector_math_64.dart';

import 'binding.dart' show SemanticsBinding;
import 'semantics_event.dart';

export 'dart:ui' show SemanticsAction;
export 'semantics_event.dart';
```

looking at the imports of semantics.dart, we're using VoidCallback that is re-exported from flutter/foundation. If we change this code so that we import from dart:ui, the errors disappear.

```
import 'dart:ui' show Offset, Rect, SemanticsAction, SemanticsFlag,
       TextDirection, VoidCallback // Added
```

I'm currently putting together a reduced reproduction, though there are a lot of moving pieces here:

- An analyzer summary containing dart:ui (web or stub_ui version).
   I've uploaded an approximate sdk here: https://drive.google.com/open?id=1bUw_e6Z7mWNSW3vh_NDQtIefrjWCFsUG
  This needs to be copied into `flutter/bin/cache/flutter_web_sdk`. note: this only contains an updated analyzer summary, actually serving the code is not expected to work.
- Check out of flutter/flutter at https://github.com/flutter/flutter/pull/29858/files
- Forked build/build_runner at https://github.com/jonahwilliams/build/tree/web_config
  - Update the dependencies overrides to point to either a local repo or the git branch.

Navigate to `dev/integration_tests/web` and run `flutter build web` - this is just a wrapper around build runner for now. The example application should compile successfully, though it won't serve as we don't currently include the precompiled sdk.

Now introduce an import of `package:flutter/widgets.dart`. The build will fail as it fails to resolve types that have been re-exported from dart:ui.

In many of these cases, navigating to the file with the "dynamic" member and adding an explicit dart:ui import will fix the issue. Note: this will completely block usage of dartdevc/hot reload workflows in mainline flutter for web targets.

**Comment by jonahwilliams** [comment]
This is possibly the same or related to internal bug b/112152456

**Comment by jonahwilliams** [comment]
cc @vsmenon @yjbanov

**Comment by scheglov** [comment]
You say "Check out of flutter/flutter at https://github.com/flutter/flutter/pull/29858/files", but I don't understand what to do. Can you clarify?

**Comment by jonahwilliams** [comment]
Sorry, I meant to link the branch https://github.com/jonahwilliams/flutter/tree/web_builders. I'll also be rolling the necessary flutter_engine and flutter code in the next few days, so It will be significantly easier to set up then.

**Comment by scheglov** [comment]
I'm probably doing something wrong, so I'm unable to build.

```
scheglov@scheglov-macbookpro4:~/tmp/555/flutter/dev/integration_tests/web (web_builders)$ /Users/scheglov/tmp/555/flutter/bin/flutter build web
Building flutter tool...
! build 1.1.1 from path /Users/scheglov/tmp/555/build/build/
! build_modules 1.0.9 from path /Users/scheglov/tmp/555/build/build_modules/
! build_runner 1.3.0-dev from path /Users/scheglov/tmp/555/build/build_runner
! build_runner_core 3.0.0-dev from path /Users/scheglov/tmp/555/build/build_runner_core/
! build_web_compilers 1.1.1 from path /Users/scheglov/tmp/555/build/build_web_compilers/
Running "flutter packages get" in web...                            1.8s
! build 1.1.1 from path /Users/scheglov/tmp/555/build/build/
! build_modules 1.0.9 from path /Users/scheglov/tmp/555/build/build_modules/
! build_runner_core 3.0.0-dev from path /Users/scheglov/tmp/555/build/build_runner_core/
! build_web_compilers 1.1.1 from path /Users/scheglov/tmp/555/build/build_web_compilers/
generating build script...                                         19.0s
Error generating build_script snapshot: file:///Users/scheglov/.pub-cache/hosted/pub.dartlang.org/build_runner-1.3.1/lib/src/generate/build.dart:63:9: Error: Type
'BuildDirectory' not found.
    Set<BuildDirectory> buildDirs,
        ^^^^^^^^^^^^^^
file:///Users/scheglov/.pub-cache/hosted/pub.dartlang.org/build_runner-1.3.1/lib/src/generate/build.dart:148:13: Error: Type 'BuildDirectory' not found.
        Set<BuildDirectory> buildDirs,
            ^^^^^^^^^^^^^^
file:///Users/scheglov/.pub-cache/hosted/pub.dartlang.org/build_runner-1.3.1/lib/src/entrypoint/options.dart:50:13: Error: Type 'BuildDirectory' not found.
  final Set<BuildDirectory> buildDirs;
            ^^^^^^^^^^^^^^
file:///Users/scheglov/.pub-cache/hosted/pub.dartlang.org/build_runner-1.3.1/lib/src/entrypoint/options.dart:135:19: Error: Type 'BuildDirectory' not found.
    @required Set<BuildDirectory> buildDirs,
                  ^^^^^^^^^^^^^^
file:///Users/scheglov/.pub-cache/hosted/pub.dartlang.org/build_runner-1.3.1/lib/src/entrypoint/options.dart:280:5: Error: Type 'BuildDirectory' not found.
Set<BuildDirectory> _parseBuildDirs(ArgResults argResults) {
    ^^^^^^^^^^^^^^
file:///Users/scheglov/.pub-cache/hosted/pub.dartlang.org/build_runner-1.3.1/lib/src/generate/watch_impl.dart:47:7: Error: Type 'BuildDirectory' not found.
  Set<BuildDirectory> buildDirs,
      ^^^^^^^^^^^^^^
file:///Users/scheglov/.pub-cache/hosted/pub.dartlang.org/build_runner-1.3.1/lib/src/generate/watch_impl.dart:121:13: Error: Type 'BuildDirectory' not found.
        Set<BuildDirectory> buildDirs,
            ^^^^^^^^^^^^^^
file:///Users/scheglov/.pub-cache/hosted/pub.dartlang.org/build_runner-1.3.1/lib/src/generate/watch_impl.dart:155:13: Error: Type 'BuildDirectory' not found.
  final Set<BuildDirectory> _buildDirs;
            ^^^^^^^^^^^^^^
file:///Users/scheglov/.pub-cache/hosted/pub.dartlang.org/build_runner-1.3.1/lib/src/entrypoint/test.dart:88:49: Error: 'BuildDirectory' isn't a type.
      var buildDirs = (options.buildDirs ?? Set<BuildDirectory>())
                                                ^^^^^^^^^^^^^^
file:///Users/scheglov/.pub-cache/hosted/pub.dartlang.org/build_runner-1.3.1/lib/src/entrypoint/test.dart:91:29: Error: Method not found: 'OutputLocation'.
            outputLocation: OutputLocation(tempPath,
                            ^^^^^^^^^^^^^^
```

**Comment by grouma** [comment]
It looks like you are using a stale `build_runner_core` package. We published v `3.0.0` which includes the `BuildDirectory` abstraction. We require this version of `build_runner_core` in `build_runner` v `>1.3.0`: https://github.com/dart-lang/build/blob/master/build_runner/pubspec.yaml#L17

**Comment by devoncarew** [comment]
From talking to @yjbanov, it may also be worth experimenting with using the DDK (kernel based) variant of DDC. If this issue is purely about DDC and analyzer summaries, you won't hit that when using DDK.

**Comment by jonahwilliams** [comment]
DDK also fails using build_runner, though my understanding is that this work isn't complete yet - so we would just be blocked on another set of issues. The analyzer summaries are also used by build_runner to do code generation FWIW

**Comment by natebosch** [comment]
> The analyzer summaries are also used by build_runner to do code generation FWIW

They are not used externally for codegen. In a DDK build analyzer summaries are not created at all.

**Comment by jonahwilliams** [comment]
interesting, good to know. If there is a branch somewhere that has a working ddk with build_runner externally?

**Comment by scheglov** [comment]
I checked out https://github.com/jonahwilliams/build and then did `git checkout web_config`. Is this what you mean saying "Forked build/build_runner at https://github.com/jonahwilliams/build/tree/web_config"?

**Comment by jonahwilliams** [comment]
Sorry for the issues on this, there are a lot of relative paths there. I've clean the example up into a single repo at  https://github.com/jonahwilliams/flutter/tree/add_dartdevc_builders.

To set this up with a local copy of flutter I would add my flutter fork as a remote and fetch from there. From the flutter directory:

```
git remote add jonah git@github.com:flutter/flutter.git
git fetch jonah
git checkout jonah/add_dartdevc_builders
```

That should get you to a version of flutter that already has everything configured properly. From there, all you need to do is `flutter build web` in `dev/integration_tests/web`

**Comment by yjbanov** [comment]
@jonahwilliams Heads up! In your instructions you are asking to set "jonah" remote to the _upstream_ flutter repo. Did you mean this:

```
git remote add jonah git@github.com:jonahwilliams/flutter.git
```

**Comment by jonahwilliams** [comment]
Woops, I would go to bed next time :)

**Comment by scheglov** [comment]
Thank you, I can reproduce the problem running `flutter build web`.

Now I will try to see how to do this in analyzer, looking into summaries, etc.

**Comment by scheglov** [comment]
I don't understand how it works.

Are all summaries stored in `.dart_tool`?
Are all summaries re-built when this directory is removed?

I see that only following libraries are linked (type inference) and pre-liked (building export namespaces, resolving references) before the export namespace for `package:flutter/foundation.dart` is requested.

How is `foundation.dartdevc.linked.sum` produced?

```
[link][libraryUris: {package:flutter/src/semantics/debug.dart, package:flutter/src/semantics/binding.dart, package:flutter/src/semantics/semantics_event.dart,
package:flutter/src/semantics/semantics.dart, package:flutter/src/semantics/semantics_service.dart}]
[prelink][package:flutter/src/semantics/debug.dart]
[prelink][package:flutter/src/semantics/binding.dart]
[prelink][package:flutter/src/semantics/semantics_event.dart]
[prelink][package:flutter/src/semantics/semantics.dart]
[prelink][package:flutter/src/semantics/semantics_service.dart]
```

**Comment by jonahwilliams** [comment]
cc @natebosch @jakemac53 , this is code uses build_web_compilers with some tiny tweaks

**Comment by jakemac53** [comment]
> Are all summaries stored in `.dart_tool`?

Yes

> Are all summaries re-built when this directory is removed?

Yes (assuming they are depended on by some app which was built)

> I see that only following libraries are linked (type inference) and pre-liked (building export namespaces, resolving references) before the export namespace for `package:flutter/foundation.dart` is requested.
>
> How is foundation.dartdevc.linked.sum produced?

We use a combination of unlinked and linked summaries from dependencies when producing a linked summary for a given module.

This is because we run 2 analyzer "phases" on each package - an unlinked summary phase and then a linked summary phase. Individual "actions" within a phase can't read the outputs of other actions in the same phase.

Because of this dependencies within the same package are provided as an unlinked summary, not a linked summary (because the linked summaries can't be read).

**Comment by natebosch** [comment]
Note that with bazel we only use linked summaries and we have a similar symptom.

**Comment by scheglov** [comment]
OK, I understand theoretically (although don't know how this happens outside analyzer) that during linking unlinked summaries of the module being linked, and unlinked and linked summaries of dependencies are used.

My confusion is that what I do debug printing in `link()` function in Analyzer, I don't see `package:flutter/foundation.dart` being linked. There is summary, but how is it produced? Is debug output with `print` disabled during this process?

**Comment by natebosch** [comment]
> Is debug output with `print` disabled during this process?

Probably - I don't remember the details but all of this is happening across the [`bazel_worker`](https://github.com/dart-lang/bazel_worker) protocol which owns `stdin`/`stdout` so it [suppressed prints](https://github.com/dart-lang/bazel_worker/blob/372d04fcadf1c356102fb3ba02c2c2e84f519fca/lib/src/worker/sync_worker_loop.dart#L32-L35)

It looks like we currently [don't print any output unless there was an error](https://github.com/dart-lang/build/blob/2a4d2d30a960f291d95daee5b4957825ea58a89a/build_modules/lib/src/summary_builder.dart#L96-L101) - @jakemac53 and I missing some other place that we would log it? Should we add some `log.info` for these?

**Comment by natebosch** [comment]
@scheglov - if you can do a `dependency_overrides` for `build_modules` to the one in [this PR](https://github.com/dart-lang/build/pull/2117) and run your build with `--verbose` I think you should be able to see the output of your `print` calls.

**Comment by jonahwilliams** [comment]
I've pushed that change into the branched version used in that PR, so you clean/update you should get it. You might need to tweak the serve command specified in the tool to pass `--verbose`

**Comment by scheglov** [comment]
I ran this:
```
git fetch jonah
git checkout jonah/add_dartdevc_builders
```

in
```
scheglov@scheglov-macbookpro4:~/tmp/666/flutter/dev/integration_tests/web ((8f750fbff...))$ git remote -v
jonah	git@github.com:jonahwilliams/flutter.git (fetch)
jonah	git@github.com:jonahwilliams/flutter.git (push)
origin	https://github.com/flutter/flutter (fetch)
origin	https://github.com/flutter/flutter (push)
```

Is this what I should do to update?
The hash is the same `8f750fbff` though, so probably not.

**Comment by jonahwilliams** [comment]
You need to update the cached override of the build_modules
```
rm bin/cache/flutter_tools.s*
flutter update-packages
flutter clean
```

**Comment by scheglov** [comment]
Sigh... I still don't see linking `package:flutter/foundation.dart` in the log.

To get debug output I change Analyzer in my Dart SDK, build it, and replace `bin/` in `flutter/bin/cache/dart-sdk/bin`, including snapshots. So, `dartanalyzer.dart.snapshot` (which I would think is used to build unlinked and linked summaries), and `dartdevc.dart.snapshot` are updated. Maybe this is not how summaries are produced?

Actually, if I knew what is used as inputs for building `foundation.dartdevc.linked.sum`, it would be even better, so I could run it outside of build and debug.

**Comment by jonahwilliams** [comment]
I updated the branches with logging of the work request as well. It looks like foundation.dartdevc.linked.sum is built here:

https://gist.github.com/jonahwilliams/e90eef5e173d5a7aca6c9105c1e93a46#file-foo-log-L952

**Comment by scheglov** [comment]
Thanks.

I can now run `analyzer --build-mode` with these linked and unlinked summaries.

One thing that I noticed is that the request does not specify neither `--dart-sdk-summary` nor `dart-sdk`, which means that it will use the Dart SDK and summaries that runs the worker, e.g. `bin/cache/dart-sdk/lib/_internal/strong.sum`. It does not have `dart:ui`.

OTOH, if I specify `--dart-sdk-summary=<cut>/flutter/bin/cache/flutter_web_sdk/flutter_web_sdk/lib/_internal/ddc_sdk.sum` explicitly, it contains `dart:ui`, so the resulting linked summary includes exports of `VoidCallback` in `package:flutter/src/foundation/basic_types.dart` and `package:flutter/foundation.dart`.

**Comment by jonahwilliams** [comment]
It works! Thank you @scheglov - I'll put together a PR to update build modules to allow configuring the summary location.

```
[INFO] Running build...
[INFO] 1.1s elapsed, 406/411 actions completed.
[INFO] 2.1s elapsed, 535/547 actions completed.
[INFO] 3.1s elapsed, 543/548 actions completed.
[INFO] Running build completed, took 4.0s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 65ms

[INFO] Succeeded after 4.1s with 471 outputs (1004 actions)

Serving `web` on http://localhost:8080

```
