### ISSUE TITLE
Uncaught TypeError: 'JSArray' is not a subtype of type 'List<ResizeObserverEntry>'

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/sdk#36798]
@kenzieschmoll commented on [Mon Apr 29 2019](https://github.com/dart-lang/html/issues/104)

I have some resize observer code that looks as follows:
```
    final observer = html.ResizeObserver(allowInterop((entries, _) {
       _details.uiEventDetails.flameChart.updateForContainerResize();
    }));
    observer.observe(element);
```
And in the dart2js version of the web app, I am getting a TypeError. I do not get this error when using `webdev serve`. 
```
Uncaught TypeError: Instance of 'JSArray': type 'JSArray' is not a subtype of type 'List<ResizeObserverEntry>'
    at Object.wrapException (main.dart.js:1115)
    at Object.assertSubtype (main.dart.js:1975)
    at EventDetails_closure.call$2 (main.dart.js:42132)
    at Object.Primitives_applyFunction (main.dart.js:1001)
    at Object.Function_apply (main.dart.js:5440)
    at _callDartFunctionFast (main.dart.js:7374)
    at main.dart.js:7365
    at Function.call$2 (main.dart.js:54318)
    at invokeClosure (main.dart.js:1307)
    at ResizeObserver.<anonymous> (main.dart.js:1325)
```

---

@rakudrama commented on [Mon Apr 29 2019](https://github.com/dart-lang/html/issues/104#issuecomment-487751354)

Can you show more of the code, especially something declared with the list type in question?

JavaScript arrays coming from JS-interop are currently considered by dart2js to implement `List<dynamic>`, which is not assignable to `List<ResizeObserverEntry>`.

I don't think this is really a html issue so much as a JS-interop issue.
There is an issue to improve these JS-interop issues:
https://github.com/dart-lang/sdk/issues/35084
And a proposal:
https://github.com/dart-lang/sdk/blob/js_interop/pkg/js/proposal.md

**Comment by kevmoo** [comment]
@kenzieschmoll @rakudrama – moved to SDK

**Comment by kenzieschmoll** [comment]
I updated the code snippet to show the entirety of the observer code. `entries` is not actually used, which is why I left it out originally.

**Comment by natebosch** [comment]
One thing to note here, the `allowInterop` call should _not_ be used.

`allowInterop` is for calls passed to `JS()` annotated methods. Calls to code in `dart:html` should not use it.

The problem remains either way.

**Comment by jacob314** [comment]
What got lost in the initial bug description is we were writing the code in that strange way to workaround a bug in dart:html.

**Comment by natebosch** [comment]
What was the bug?

**Comment by morrica** [comment]
What is the status of this issue? I have something that looks similiar with the latest dart sdk v2.6.1.
The following code works fine with `webdev serve` (dartdevc), but fails with `webdev build` (dart2js).

Code Snippet:
```dart
@override
  void ngOnInit() {
    _resizeObserver = ResizeObserver((List<ResizeObserverEntry> entries, ResizeObserver observer) {
      if(_chart != null) {
        try {
          _chart.resize();
        } catch(error) {
          log.warning("Unable to resize _chart because $error");
        }
      }
    });
    _resizeObserver.observe(chartRef);
  }
```
As I said, the above works fine with dartdevc, but with dart2js it fails with the following error each time the window size changes.

```
Uncaught TypeError: Instance of 'minified:f2': type 'minified:f2' is not a subtype of type 'List<minified:iu>'
    at Object.h (main.dart.js:477)
    at Object.f (main.dart.js:824)
    at wv.$2 (main.dart.js:16940)
    at Z0 (main.dart.js:553)
    at ResizeObserver.<anonymous> (main.dart.js:560)
```

I apologize for the minified code. I have been unable to force `webdev build` to build without minification or get source-maps working with the command.

My code is not using `allowInterop()` so perhaps I should file a separate issue for this?

**Comment by sigmundch** [comment]
Thanks for following up! Indeed it appears like that case was accidentally omitted. I sent https://dart-review.googlesource.com/c/sdk/+/127500 to include it too.
