### ISSUE TITLE
Binary file from dart2native can't be used from Linux's path

### ISSUE THREAD

**Issue by BLeAm** [dart-lang/sdk#38912]
The single binary files that created with dart2native can't be put and used from Linux's path, it will print the usage message instead, like:
```bash
$ dart2native hello.dart
Generated: /home/blahblah/hello.exe

$ ./hello.exe
hello world

$ sudo mv hello.exe /usr/local/bin
$ hello.exe
Usage: dart [<vm-flags>] <dart-script-file> [<script-arguments>]
```

I've found this issue with Dart 2.6.0-dev.7.0  on Linux.

**Comment by cskau-g** [comment]
Thank you for reporting this issue. I'm investigating.

In the meantime, can I get you to test if you're able to work around the issue by running the binary via a path instead of just the binary name? I.e.:
`$ cd /usr/local/  ;  bin/hello.exe`
or
`$ /usr/local/bin/hello.exe`
or even
```
$ `which hello.exe`
```

**Comment by BLeAm** [comment]
Both ways of running it, from absolute/relative-path, work correctly.
Thank you for pointing out the workaround.

**Comment by cskau-g** [comment]
This should now have been fixed at HEAD so I'll go ahead and close this issue.
Note that it might still be a short while before the fix lands in dev and stable releases.

**Comment by Ephenodrom** [comment]
Does someone know if version 2.7.0 already includes this fix ? I think i have the same problem after generating an executable on Ubuntu and uploading it via SCP to a Debian machine. I try to run the executable on the Debian machine and it prints out the usage message.

**Comment by Ephenodrom** [comment]
@cskau-g Do you have any information about my question ?

**Comment by Ephenodrom** [comment]
@cskau-g I tried it again with version 2.7.1 but still the same problem.

> Does someone know if version 2.7.0 already includes this fix ? I think i have the same problem > after generating an executable on Ubuntu and uploading it via SCP to a Debian machine. I try to run > the executable on the Debian machine and it prints out the usage message.

**Comment by cskau-g** [comment]
@Ephenodrom, It should work in 2.7.1, yes. Testing it locally confirms this as well.

It is of course possible you're running into a separate problem.
Are both systems X64? Perhaps there are some significant differences between the libc/kernels that cause loading the embedded ELF to fail?

You could try testing dart2native locally on your Debian system and verify you can at least run executables built there.

If you continue to experience issues like this, feel free to start a new issue to track this.
But in that case please include as much information about the systems as possible, to help make debugging a little easier.

Thanks.

**Comment by Ephenodrom** [comment]
Hello @cskau-g 
I think the problem comes from a different issue and i think it is more of a problem of my webhosting server where i have limited access to the OS it is running on. I opened another issue to make it clear whether is is a bug or a problem from my site.

https://github.com/dart-lang/sdk/issues/40405
