### ISSUE TITLE
`Function` equals broken on DDC

### ISSUE THREAD

**Issue by dnfield** [dart-lang/sdk#45762]
For example

```dart
void main() {
  Function f1 = () { print('f1'); };
  Function f2 = () { print('f2'); };

  print(f1 == f2);
}
```

Using `flutter run -d chrome`, the output is:

```
TypeError: f1._equals is not a function
    at main$
    (http://localhost:50135/packages/ddc_bug/main.dart.lib.js:21:19)
    at main (http://localhost:50135/web_entrypoint.dart.lib.js:33:29)
    at main.next (<anonymous>)
    at http://localhost:50135/dart_sdk.js:37387:33
    at _RootZone.runUnary (http://localhost:50135/dart_sdk.js:37258:59)
    at _FutureListener.thenAwait.handleValue
    (http://localhost:50135/dart_sdk.js:32514:29)
    at handleValueCallback (http://localhost:50135/dart_sdk.js:33041:49)
    at Function._propagateToListeners
    (http://localhost:50135/dart_sdk.js:33079:17)
    at _Future.new.[_completeWithValue]
    (http://localhost:50135/dart_sdk.js:32927:23)
    at http://localhost:50135/dart_sdk.js:32178:46
    at _RootZone.runUnary (http://localhost:50135/dart_sdk.js:37258:59)
    at _FutureListener.then.handleValue
    (http://localhost:50135/dart_sdk.js:32514:29)
    at handleValueCallback (http://localhost:50135/dart_sdk.js:33041:49)
    at Function._propagateToListeners
    (http://localhost:50135/dart_sdk.js:33079:17)
    at _Future.new.[_completeWithValue]
    (http://localhost:50135/dart_sdk.js:32927:23)
    at async._AsyncCallbackEntry.new.callback
    (http://localhost:50135/dart_sdk.js:32948:35)
    at Object._microtaskLoop (http://localhost:50135/dart_sdk.js:37510:13)
    at _startMicrotaskLoop (http://localhost:50135/dart_sdk.js:37516:13)
    at http://localhost:50135/dart_sdk.js:33287:9
```

This exists in Flutter beta onward, but not Flutter stable. I have not bisected further. The error does not occur (and the print is as expected) in release/profile mode, which doesn't use DDC.

**Comment by dnfield** [comment]
I think this might exist in stable ... if I'm checking correctly anyway. Trying to figure out where to bisect this from.

**Comment by dnfield** [comment]
For reasons I do not understand, my mimimal example fails even on Flutter stable, but `petit_parser` does not fail.

**Comment by dnfield** [comment]
Here's a minimal repro that still works on stable:

```dart
void main() {
  final f1 = FunctionHolder(() {
    print('f1');
  });
  final f2 = FunctionHolder(() {
    print('f2');
  });

  print(f1 == f2);
}

class FunctionHolder {
  FunctionHolder(this.function);

  final Function function;

  @override
  bool operator ==(Object other) {
    return other is FunctionHolder && other.function == function;
  }

  @override
  int get hashCode => function.hashCode;
}
```

Not sure why the indirection matters. The example in the main body fails, but they seem to be the same root cuase.

**Comment by dnfield** [comment]
Started with flutter/flutter#77816, which contained dart roll https://github.com/flutter/engine/pull/24907, which was https://dart.googlesource.com/sdk.git/+log/64a5583ffbc9..8f22201e4050

**Comment by dnfield** [comment]
Cause of https://github.com/petitparser/dart-petitparser/issues/103

**Comment by dnfield** [comment]
This is probably fixed by https://github.com/dart-lang/sdk/commit/8e2539d24c93ebb238c8681250ab67c4bf19c4e9... Which will roll into flutter here: https://github.com/flutter/engine/pull/25665

**Comment by vsmenon** [comment]
@nshahan @sigmundch @franklinyow - we should consider cherry picking Nick's change to get it into the coming stable.  Per @dnfield , it (probably) fixes a regression since the current stable.

**Comment by dnfield** [comment]
The latest Dart roll into Flutter (which contains the fix) makes both test cases in this bug pass.

**Comment by sigmundch** [comment]
Thanks for verifying @dnfield - indeed this was meant to be fixed by that commit. I'm marking this issue as closed since the fix landed, but I also filed this cherry pick for the beta channel: https://github.com/dart-lang/sdk/issues/45772

**Comment by lukepighetti** [comment]
This issue is prevalent on `dev` branch. How do we track the progress of this issue so we can make a guess of when it will be available?

```
Flutter 2.2.0-10.1.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision 0941968447 (11 days ago) • 2021-04-15 12:01:02 -0700
Engine • revision d2a2e93510
Tools • Dart 2.13.0 (build 2.13.0-211.6.beta)
```

**Comment by dnfield** [comment]
The cherry picked commit has to first roll into Dart's beta, and then eventually will get to Flutter. I don't believe that's happened yet - though should be fixed on `master`.

It should be available on dev in the next dev roll.

**Comment by lukepighetti** [comment]
So just for my education, `beta` gets cherry picked fixes, but `dev` has to wait for roll?

**Comment by vsmenon** [comment]
This particular fix has rolled into Dart's dev and beta branches.  We (usually!) wait for a fix to roll successfully into the former before we cherry-pick into the latter.  There is also some delay before those go out on Flutter's dev and beta channels respectively.

Sorry for the confusion.  We still have some work to do to make these cross-repo releases cleaner and more transparent.

**Comment by lukepighetti** [comment]
Hate to ping this topic again, but dev branch is 11 days old and our latest dev release is 11 days old. I think dev channel is up to date with dev branch. Either the cherry pick didn't make it to dev or I'm missing visibility on something. I haven't been able to find anyone who knows how to determine where these things are and what their timeline is. Can someone please help me get some visibility on where this fix is in relation to the `dev` channel?

**Comment by lukepighetti** [comment]
Ah I must be getting dart/sdk and flutter/flutter mixed up. How do we determine when a fix in dart/sdk makes its way into flutter/flutter?

**Comment by dnfield** [comment]
Dart rev rolled into Flutter engine in https://github.com/flutter/engine/pull/25665. On that page, you can see a link towards the bottom that -

Flutter engine rolled into framework in https://github.com/flutter/flutter/pull/80769

on that page, you can see it landed as commit https://github.com/flutter/flutter/commit/3ff6e4b2769e0ae5d37d03e79c0d429dbadcbeab, and on that page you can see it's in 
![image](https://user-images.githubusercontent.com/8620741/116292628-c0438100-a74a-11eb-9782-dde28a5faf47.png)

Which is the 2.3 dev release.

There may need to be some additional work on the Flutter side to make sure Dart's CP gets CP'd by Flutter, but if you want this now, using the latest Flutter dev branch should get it for you.

**Comment by dnfield** [comment]
@christopherfujino just informed me that this particular change will be going out in a beta hotfix release pretty soon.
