### ISSUE TITLE
Webdev 2.7.6 with DDS 2.1.6 crash

### ISSUE THREAD

**Issue by AndrewLugg** [dart-lang/sdk#47978]
This tracker is for issues related to:

* Webdev 2.7.5 and 2.7.6
* DDS 2.1.6

In your issue, please include:

* Dart SDK Version: 2.14.1
* Windows and Linux (that I have seen)

On Dart version 2.14.1 webdev won't work anymore because it will try load DDS 2.1.6 which throws an exception when you try to activate webdev. It works fine in 2.15.1 of dart.

Here is the logs from when you try to activate webdev:
```
+ pub global activate webdev
Resolving dependencies...
+ args 2.3.0
+ async 2.8.2
+ browser_launcher 1.0.0
+ build_daemon 3.0.1
+ built_collection 5.1.1
+ built_value 8.1.3
+ charcode 1.3.1
+ checked_yaml 2.0.1
+ clock 1.1.0
+ collection 1.15.0
+ convert 3.0.1
+ crypto 3.0.1
+ dds 2.1.6 (2.1.6+1 available)
+ devtools 2.8.0 (2.9.2 available)
+ devtools_server 2.8.0 (2.9.2 available)
+ devtools_shared 2.8.0 (2.9.2 available)
+ dwds 11.5.0 (11.5.1 available)
+ fixnum 1.0.0
+ http 0.13.4
+ http_multi_server 3.0.1
+ http_parser 4.0.0
+ intl 0.17.0
+ io 1.0.3
+ json_annotation 4.4.0
+ json_rpc_2 3.0.1
+ logging 1.0.2
+ meta 1.7.0
+ mime 1.0.1
+ package_config 2.0.2
+ path 1.8.1
+ pedantic 1.11.1 (discontinued replaced by lints)
+ pool 1.5.0
+ pub_semver 2.1.0
+ pubspec_parse 1.2.0
+ shelf 1.2.0
+ shelf_packages_handler 3.0.0
+ shelf_proxy 1.0.1
+ shelf_static 1.1.0
+ shelf_web_socket 1.0.1
+ source_maps 0.10.10
+ source_span 1.8.1
+ sse 4.1.0
+ stack_trace 1.10.0
+ stream_channel 2.1.0
+ stream_transform 2.0.0
+ string_scanner 1.1.0
+ term_glyph 1.2.0
+ typed_data 1.3.0
+ usage 4.0.2
+ uuid 3.0.5
+ vm_service 7.5.0 (8.1.0 available)
+ watcher 1.0.1
+ web_socket_channel 2.1.0
+ webdev 2.7.6 (2.7.7 available)
+ webkit_inspection_protocol 1.0.0
+ yaml 3.1.0
Downloading webdev 2.7.6...
Downloading dds 2.1.6...
Downloading uuid 3.0.5...
Building package executables...
Failed to build webdev:webdev:
../../.pub-cache/hosted/pub.dartlang.org/dds-2.1.6/lib/src/cpu_samples_manager.dart:54:21: Error: Type 'CpuSamplesEvent' not found.
  void cacheSamples(CpuSamplesEvent samples) {
                    ^^^^^^^^^^^^^^^
../../.pub-cache/hosted/pub.dartlang.org/dds-2.1.6/lib/src/cpu_samples_manager.dart:54:21: Error: 'CpuSamplesEvent' isn't a type.
  void cacheSamples(CpuSamplesEvent samples) {
                    ^^^^^^^^^^^^^^^
```

This only occurs with 2.14.1 of dart. DDS 2.1.4 is also fine, but when you activate webdev it automatically tries to grab newest DDS.

This is also patched with 2.1.6+1 of DDS, but webdev isn't pulling that version.

**Comment by sigmundch** [comment]
/cc @bkonyi 

My understanding is that this issue is because `dds-2.1.6` had an invalid constraint to depend on version `^7.5.0` of `vm_service`. As a result the installed packages are inconsistent when using webdev. The invalid constraint was fixed in `2.1.6+1` (BTW @bkonyi, it appears this version is not submitted in the SDK repo), but `webdev` doesn't choose this version because it too was constraint to use a version of `vm_service` older than `8.0.0`. As a result, webdev is selecting `2.1.6`.

I can imagine couple ways to address this:
* roll forward on webdev to allow vm_service 8.1. Not sure if this will require any changes though. Note that a few folks are OOO on our side and wont be able to publish a new webdev until sometime in January.
* look into hide the invalid dds-2.1.6 entirely. Is there an option to remove the published version from pub? If not, could we publish 2.1.6+2 that reverts to the old 2.1.5 behavior and a new 2.1.7 that matches 2.1.6+1? That way webdev (and any other package with similar constraints) will properly fetch 2.1.6+2 and elide the packages with the incorrect constrant.

**Comment by bkonyi** [comment]
@sigmundch `dds-2.1.6` was retracted and is no longer available on pub. You might have to run `dart pub global deactivate webdev` and then re-activate in order to get back into a good state.

**Comment by sigmundch** [comment]
Thanks @bkonyi ! Awesome to hear we do have a mechanism to retract packages now :)

@AndrewLugg - I believe that should address your issue, let us know if it doesn't.

**Comment by AndrewLugg** [comment]
I just tested this, it will still grab `2.1.6` from pub. Although if you look on the pub.dev that version has been removed.

I ran a pub cache clean to make sure it wasn't just grabbing the cached package, but the issue still occurs. Here is a copy of the process.

```
andrew@Andrew-Laptop:~$ dart pub cache clean
This will remove everything inside /home/andrew/.pub-cache.
You will have to run `dart pub get` again in each project.
Are you sure? (y/N)? y
Removing pub cache directory /home/andrew/.pub-cache.
andrew@Andrew-Laptop:~$ pub global activate webdev
Resolving dependencies... (3.4s)
+ args 2.3.0
+ async 2.8.2
+ browser_launcher 1.0.0
+ build_daemon 3.0.1
+ built_collection 5.1.1
+ built_value 8.1.3
+ charcode 1.3.1
+ checked_yaml 2.0.1
+ clock 1.1.0
+ collection 1.15.0
+ convert 3.0.1
+ crypto 3.0.1
+ dds 2.1.6 (2.1.6+1 available)
+ devtools 2.8.0 (2.9.2 available)
+ devtools_server 2.8.0 (2.9.2 available)
+ devtools_shared 2.8.0 (2.9.2 available)
+ dwds 11.5.0 (11.5.1 available)
+ fixnum 1.0.0
+ http 0.13.4
+ http_multi_server 3.0.1
+ http_parser 4.0.0
+ intl 0.17.0
+ io 1.0.3
+ json_annotation 4.4.0
+ json_rpc_2 3.0.1
+ logging 1.0.2
+ meta 1.7.0
+ mime 1.0.1
+ package_config 2.0.2
+ path 1.8.1
+ pedantic 1.11.1 (discontinued replaced by lints)
+ pool 1.5.0
+ pub_semver 2.1.0
+ pubspec_parse 1.2.0
+ shelf 1.2.0
+ shelf_packages_handler 3.0.0
+ shelf_proxy 1.0.1
+ shelf_static 1.1.0
+ shelf_web_socket 1.0.1
+ source_maps 0.10.10
+ source_span 1.8.1
+ sse 4.1.0
+ stack_trace 1.10.0
+ stream_channel 2.1.0
+ stream_transform 2.0.0
+ string_scanner 1.1.0
+ term_glyph 1.2.0
+ typed_data 1.3.0
+ usage 4.0.2
+ uuid 3.0.5
+ vm_service 7.5.0 (8.1.0 available)
+ watcher 1.0.1
+ web_socket_channel 2.1.0
+ webdev 2.7.6 (2.7.7 available)
+ webkit_inspection_protocol 1.0.0
+ yaml 3.1.0
Downloading webdev 2.7.6...
Downloading sse 4.1.0...
Downloading pool 1.5.0...
Downloading browser_launcher 1.0.0...
Downloading webkit_inspection_protocol 1.0.0...
Downloading stack_trace 1.10.0...
Downloading yaml 3.1.0...
Downloading collection 1.15.0...
Downloading string_scanner 1.1.0...
Downloading shelf_static 1.1.0...
Downloading http_parser 4.0.0...
Downloading typed_data 1.3.0...
Downloading shelf_proxy 1.0.1...
Downloading pub_semver 2.1.0...
Downloading path 1.8.1...
Downloading http_multi_server 3.0.1...
Downloading crypto 3.0.1...
Downloading source_span 1.8.1...
Downloading term_glyph 1.2.0...
Downloading mime 1.0.1...
Downloading convert 3.0.1...
Downloading pubspec_parse 1.2.0...
Downloading checked_yaml 2.0.1...
Downloading logging 1.0.2...
Downloading io 1.0.3...
Downloading charcode 1.3.1...
Downloading json_annotation 4.4.0...
Downloading shelf 1.2.0...
Downloading stream_channel 2.1.0...
Downloading meta 1.7.0...
Downloading dwds 11.5.0...
Downloading shelf_packages_handler 3.0.0...
Downloading vm_service 7.5.0...
Downloading web_socket_channel 2.1.0...
Downloading shelf_web_socket 1.0.1...
Downloading package_config 2.0.2...
Downloading built_collection 5.1.1...
Downloading http 0.13.4...
Downloading args 2.3.0...
Downloading json_rpc_2 3.0.1...
Downloading dds 2.1.6...
Downloading async 2.8.2...
Downloading pedantic 1.11.1...
Downloading devtools_shared 2.8.0...
Downloading usage 4.0.2...
Downloading build_daemon 3.0.1...
Downloading stream_transform 2.0.0...
Downloading watcher 1.0.1...
Downloading built_value 8.1.3...
Downloading fixnum 1.0.0...
Downloading uuid 3.0.5...
Downloading devtools 2.8.0...
Downloading devtools_server 2.8.0...
Downloading intl 0.17.0...
Downloading clock 1.1.0...
Downloading source_maps 0.10.10...
Building package executables... (2.0s)
Failed to build webdev:webdev:
.pub-cache/hosted/pub.dartlang.org/dds-2.1.6/lib/src/cpu_samples_manager.dart:54:21: Error: Type 'CpuSamplesEvent' not found.
  void cacheSamples(CpuSamplesEvent samples) {
                    ^^^^^^^^^^^^^^^
.pub-cache/hosted/pub.dartlang.org/dds-2.1.6/lib/src/cpu_samples_manager.dart:54:21: Error: 'CpuSamplesEvent' isn't a type.
  void cacheSamples(CpuSamplesEvent samples) {
                    ^^^^^^^^^^^^^^^
```

**Comment by sigmundch** [comment]
Thanks for following up @AndrewLugg 

@bkonyi - any ideas?

/cc @jonasfj - in case this is a pub issue?

**Comment by bkonyi** [comment]
No clue, unfortunately. `2.1.6` isn't even listed anymore so it shouldn't be resolving... :-/

**Comment by sigmundch** [comment]
Ah - I just connected the fact that package retraction is not supported in SDKs prior to Dart 2.15 (documented in https://dart.dev/tools/pub/publishing#retract) and @AndrewLugg is using 2.14.1.

Seems like you were also able to use a newer SDK. Are you able to switch to that newer SDK and are unblocked? If so, I'm inclined to close again the bug and mark this as working as intended. If however many folks can't migrate to the latest stable release and this is blocking development, we should resort to the older style of fixes (e.g. publishing patch releases of dds or webdev to shadow the version inconsistency).

**Comment by AndrewLugg** [comment]
We are unable to migrate to 2.15.1 as we support schools and they like to use old devices and still use iOS 9. 2.15.1 doesn't work on iOS 9. 2.14.1 does but only non-minified and null-safety off.

**Comment by bkonyi** [comment]
I've re-uploaded `dds` `2.1.5` as `2.1.6+2` and `2.1.6+1` as `2.1.7` with the right dependencies which should fix things for you @AndrewLugg. Sorry for the hassle!

- Revert to `2.1.5` (now `2.1.6+2`) state [CL](https://dart-review.googlesource.com/c/sdk/+/225640)
- Reland `2.1.6+1` as `2.1.7` [CL](https://dart-review.googlesource.com/c/sdk/+/225641)

**Comment by sigmundch** [comment]
Thank you @bkonyi!

**Comment by alextekartik** [comment]
> which should fix things 

The issue was close but I'm not sure whether this is fixed though. I still cannot activate webdev. Is it a different issue?

**Comment by sigmundch** [comment]
Just to post here the same update from https://github.com/dart-lang/webdev/issues/1482#issuecomment-1005077827 - it appears that an additional release of dds-2.1.6+3 was needed. @bkonyi published that yesterday so we hope this is now fully resolved.
