### ISSUE TITLE
[CP] Suggest static fields/getters, setState().

### ISSUE THREAD

**Issue by scheglov** [dart-lang/sdk#49239]
### Commit(s) to merge

https://dart-review.googlesource.com/c/sdk/+/248080

### Target

stable

### Issue Description

This includes fixes for completions:
1. Suggest static fields when the context type matches.
2. A fix for the context type.
3. A fix for `setState` completion.

### What is the fix

These fixes were done in the master, but we need them in stable as well.

### Why cherry-pick

Static field suggestions are useful for suggesting `Colors` for example in Flutter code.
And `setState()` is also used very often.

@bwilkerson @jacob314 

### Risk

low

### Issue link(s)

https://github.com/dart-lang/sdk/issues/49233
https://github.com/dart-lang/sdk/issues/49054#issuecomment-1152957677
https://github.com/dart-lang/sdk/issues/49054

**Comment by devoncarew** [comment]
@itsjustkevin - pinging just to make sure this is reviewed by the dart scrum

**Comment by itsjustkevin** [comment]
@vsmenon @athomas @devoncarew

**Comment by vsmenon** [comment]
This is a fairly big CL.  Do we want to give this more bake time?  Do we have feedback that it works from users?

**Comment by sigmundch** [comment]
At a first glance the description may give the impression here that this is new feature work, but it appears this is more to address an important regression (if I understand correctly the related bugs) - @scheglov can you confirm and share some details to clarify how bad the regression is?

**Comment by scheglov** [comment]
Yes, this CP contains fixes for regressions.

The biggest one is absence of suggesting static fields, so you cannot type `color: blue^` and get `Colors.blue` suggestion and others. The same is for alignment. With the fix it works again:
<img width="730" alt="image" src="https://user-images.githubusercontent.com/384794/174340223-51992728-baca-4092-9eeb-de4b3b8b6756.png">

Another unpleasant regression that was fixed is `setState` suggestion, which we special-cased in suggestions builder (long time ago), but did not support specially in the new protocol (when the regression happened). So, the users don't get `setState` at all. This is quite bad, it must be an often used invocation.

The fix for the context type of a named argument is necessary for the static fields suggestions to work, and is very small.

The last fix is suggestions in URIs, so that when there are many URIs (many packages available in `pubspec.yaml`), we filter them by name correctly. I think this one is less important, but it is not big as well.

All these fixes are already done in the master. As for backing, I'm not sure that this helps. These regressions were present for a couple of months, and nobody noticed or reported them until after stable release. So, maybe nobody uses anything other than stable, or nobody cares.

**Comment by khanahsan** [comment]
[Code suggestion for async/dispose/setState no longer works in Flutter 3.0.2 #106724
](https://github.com/flutter/flutter/issues/106724)
i'm still face this issue in Android Studio i use dart 2.17.3 version

**Comment by xshiwei** [comment]
Also invalid in version 3.0.4

**Comment by vsmenon** [comment]
lgtm

**Comment by whesse** [comment]
This was picked into stable 2.17.6
