### ISSUE TITLE
Dart2Wasm compiler fails building when dart:ffi library is conditionally imported

### ISSUE THREAD

**Issue by sroddy** [dart-lang/sdk#55948]
When compiling a simple flutter project in wasm using the latest dart stable version, the compiler will refuse building once a library that conditionally imports "dart:ffi" is imported and used.

simple steps to reproduce

main.dart:
```dart
import 'e.dart';

void main() {
  print(e());
}
```

e.dart:
```dart
export 'e_stub.dart' if (dart.library.ffi) 'e_ffi.dart';
```

e_stub.dart:
```dart
String e() => 'hello';
```

e_ffi.dart:
```dart
import 'dart:ffi';
String e() => 'hello';
```

interestingly enough, if the e.dart file is rewritten like this...

e.dart:
```dart
export 'e_ffi.dart' if (dart.library.js_interop) 'e_stub.dart';
```

...the compiler doesn't complain

**Comment by dcharkes** [comment]
cc @mkustermann @eyebrowsoffire

**Comment by mkustermann** [comment]
This is a known issue and comes due to the fact that the library `dart:ffi` is actually available but we disallow importing it in newest versions (because we only have sketchy support for a subset of it atm - it's not generally working). It's not a specific issue to `dart:ffi` but also for `dart:js` / `dart:js_util` / ...

We could avoid this issue if we made it an internal library (i.e. `dart:_ffi`). Though this not so easy to do due to a few reasons (among them rolling such a change into flutter engine - which currently uses `dart:ffi` imports interop).

The conditional import mechanism works in the earlier stages than the backend mechanism that disallows importing certain (somewhat existing) libraries. We could investigate whether we can do that part earlier in the pipeline (/cc @osa1)

Using `dart.library.js_interop` is the condition we recommend for packages that work on web/js-environments.

**Comment by mkustermann** [comment]
I've made a few changes that will make us be able to evaluate the conditional import correctly (and thereby `dart.library.ffi` being `false`).  Once [cl/370580](https://dart-review.googlesource.com/c/sdk/+/370580) lands and rolls up to flutter it should address these issues.

**Comment by mkustermann** [comment]
The CL landed and will make it's way up to flutter main channel in the coming days.

In the meantime I've filed for a cherry-pick request to stable channel in [Issue 55979](https://github.com/dart-lang/sdk/issues/55979)

**Comment by haorendashu** [comment]
@mkustermann Hello, can we rollback the local flutter version to avoid this issue? And whick version flutter can we rollback to?

**Comment by mkustermann** [comment]
> @mkustermann Hello, can we rollback the local flutter version to avoid this issue? And whick version flutter can we rollback to?

Due to incomplete and unstable ffi in dart2wasm we made two changes, here's the commits and how they rolled:
* Prevent importing `dart:ffi` (dart-lang/sdk@dbcf23a5ed935ab67659930a526c3e2aea6c60fc, engine: flutter/engine@b0f4d74597087fd4cb11417767bf9fd8bbee2238, flutter/flutter@1dbf953a5ae29ed114e58686bf109ee11a2fcb42)
* Fix incorrectly evaluated conditional imports using `dart.library.ffi` (dart-lang/sdk@847c35612ad295f44b5d6e1b061f7423efa817cf, flutter/engine@6370add796e7b556c9c63e0f995b07d0ba7614ef, flutter/flutter@cc24f877dbc115693e5bae7885d0fc09a47bdafb) (this issue)

So you can use versions of flutter before those if you really want to. But there's a reason we have disallowed it, so I can discourage relying on it until we have a properly working FFI for the web.

**Comment by fvisticot** [comment]
> > @mkustermann Hello, can we rollback the local flutter version to avoid this issue? And whick version flutter can we rollback to?
> 
> Due to incomplete and unstable ffi in dart2wasm we made two changes, here's the commits and how they rolled:
> 
> * Prevent importing `dart:ffi` ([dbcf23a](https://github.com/dart-lang/sdk/commit/dbcf23a5ed935ab67659930a526c3e2aea6c60fc), engine: [flutter/engine@b0f4d74](https://github.com/flutter/engine/commit/b0f4d74597087fd4cb11417767bf9fd8bbee2238), [flutter/flutter@1dbf953](https://github.com/flutter/flutter/commit/1dbf953a5ae29ed114e58686bf109ee11a2fcb42))
> * Fix incorrectly evaluated conditional imports using `dart.library.ffi` ([847c356](https://github.com/dart-lang/sdk/commit/847c35612ad295f44b5d6e1b061f7423efa817cf), [flutter/engine@6370add](https://github.com/flutter/engine/commit/6370add796e7b556c9c63e0f995b07d0ba7614ef), [flutter/flutter@cc24f87](https://github.com/flutter/flutter/commit/cc24f877dbc115693e5bae7885d0fc09a47bdafb)) (this issue)
> 
> So you can use versions of flutter before those if you really want to. But there's a reason we have disallowed it, so I can discourage relying on it until we have a properly working FFI for the web.

I'm a bit lost.
I have updated dart to 3.4.4 and try to update my web project including flutter_svg package (using vector_graphics_compiler)

I get the following error:
```

../.pub-cache/hosted/pub.dev/vector_graphics_compiler-1.1.11+1/lib/src/svg/_tessellator_ffi.dart:6:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi' as ffi;
^
../.pub-cache/hosted/pub.dev/vector_graphics_compiler-1.1.11+1/lib/src/svg/_path_ops_ffi.dart:6:1: Error: 'dart:ffi' can't be imported when compiling to Wasm.
import 'dart:ffi' as ffi;
^
```

What can I do to fix this issue ?

**Comment by nietsmmar** [comment]
> What can I do to fix this issue ?

You have to build current flutter from git on your own. Or wait for the fix to be in the next version.

**Comment by mkustermann** [comment]
> I get the following error:
> ```
> ../.pub-cache/hosted/pub.dev/vector_graphics_compiler-1.1.11+1/lib/src/svg/_tessellator_ffi.dart:6:1: Error:
>  'dart:ffi' can't be imported when compiling to Wasm.
> import 'dart:ffi' as ffi;
> ```
> What can I do to fix this issue ?

This particular issue in `package:vector_graphics_compiler` is due to a conditional import that was incorrectly evaluated in the compiler (see [packages:vector_graphics_compiler/src/svg/tessellator.dart](https://github.com/dnfield/vector_graphics/blob/357db2575ebbf64280e792228af6724e3d9ef0e9/packages/vector_graphics_compiler/lib/src/svg/tessellator.dart#L7)). The bug was fixed in https://github.com/dart-lang/sdk/commit/847c35612ad295f44b5d6e1b061f7423efa817cf and should be available on flutter main/master channel. As mentioned above flutter may be slow atm to release new stable channel versions (which is why this fix isn't available there yet)

That being said, `package:vector_graphics_compiler` has other conditional imports (see e.g. [package:vector_graphics_compiler/vector_graphics_compiler.dart](https://github.com/dnfield/vector_graphics/blob/main/packages/vector_graphics_compiler/lib/vector_graphics_compiler.dart#L32)) depending on `dart.library.html` (i.e. `dart:html` - the legacy API to talk to the DOM). We discourage usage of `dart:html` and instead want users to migrate to our new static JS interop APIs (and `package:web` which provides dom APIs using static interop).  dart2wasm doesn't support `dart:html` - so this package would need to be migrated to static JS interop. Unfortunately the owner of this package is unavailable.

**Comment by kevmoo** [comment]
See also https://github.com/dnfield/vector_graphics/issues/244

**Comment by chandrabezzo** [comment]
@mkustermann I try using `3.23.0-13.0.pre.337`, but the issue still happen. I found the issue `Error: 'dart:ffi' can't be imported when compiling to Wasm.`. We need to improve the code for every package/plugin that we use?

**Comment by chandrabezzo** [comment]
But this issue fixed in 3.22.1

**Comment by mkustermann** [comment]
> But this issue fixed in 3.22.1
> ...
> @mkustermann I try using 3.23.0-13.0.pre.337, but the issue still happen. I found the issue Error: 'dart:ffi' can't be imported when compiling to Wasm.. We need to improve the code for every package/plugin that we use?

Please see my response here: https://github.com/flutter/flutter/issues/149984#issuecomment-2191014653

Locking this issue for more comments due to
* master/main is working as intended (as far as I'm aware of) 
* the changes will eventually make it to stable channel (either via flutter team cherry-picking new dart stable version or making new stable branch cut)
* The problem with `package:flutter_svg` and `package:vector_graphics_compiler` needs changes in those packages, which is tracked https://github.com/dnfield/vector_graphics/issues/244
